In [1]:
import pandas as pd

protein_gene_list='/Users/irffanalahi/Research/Research_update/GENE/processingWithUCSC/mart_export.txt_bed_filterdedWith_protein-coding_gene_name.txt_sorted'
tobefiltered='/Users/irffanalahi/Research/Research_update/GENE/processingWithUCSC/v2/intron_genecode_v36_modified.txt_canonical.txt'

outfile=tobefiltered+"_proteinCodingGene.txt"

protein_gene_listdf=pd.read_csv(protein_gene_list,sep='\t',header=None)
tobefiltereddf=pd.read_csv(tobefiltered,sep='\t')

In [2]:
protein_gene_listdf.head()

      0       1       2       3
0  chr1   65419   71585   OR4F5
1  chr1  450703  451697  OR4F29
2  chr1  685679  686673  OR4F16
3  chr1  923928  944581  SAMD11
4  chr1  944203  959309   NOC2L

In [3]:
protein_gene_listdf.rename(columns={3:'hg38.kgXref.geneSymbol'},inplace=True)
protein_gene_listdf.head()

      0       1       2 hg38.kgXref.geneSymbol
0  chr1   65419   71585                  OR4F5
1  chr1  450703  451697                 OR4F29
2  chr1  685679  686673                 OR4F16
3  chr1  923928  944581                 SAMD11
4  chr1  944203  959309                  NOC2L

In [4]:
prot_allgenes=list(set(protein_gene_listdf['hg38.kgXref.geneSymbol'].tolist()))
len(prot_allgenes)

19104

In [5]:
tobefiltereddf.head()

,#hg38.knownCanonical.chrom_x,hg38.knownCanonical.chromStart_x,hg38.knownCanonical.chromEnd_x,hg38.knownCanonical.transcript,transcriptno,direction,#hg38.knownCanonical.chrom_y,hg38.knownCanonical.chromStart_y,hg38.knownCanonical.chromEnd_y,hg38.kgXref.geneSymbol
0,chr1,12227,12612,ENST00000456328.2,0,+,chr1,11868,14409,DDX11L1
1,chr1,12721,13220,ENST00000456328.2,1,+,chr1,11868,14409,DDX11L1
2,chr1,14501,15004,ENST00000488147.1,0,-,chr1,14403,29570,WASH7P
3,chr1,15038,15795,ENST00000488147.1,1,-,chr1,14403,29570,WASH7P
4,chr1,15947,16606,ENST00000488147.1,2,-,chr1,14403,29570,WASH7P

In [6]:
outdf=tobefiltereddf.merge(protein_gene_listdf,how='inner',on=['hg38.kgXref.geneSymbol'])
outdf.head()

,#hg38.knownCanonical.chrom_x,hg38.knownCanonical.chromStart_x,hg38.knownCanonical.chromEnd_x,hg38.knownCanonical.transcript,transcriptno,direction,#hg38.knownCanonical.chrom_y,hg38.knownCanonical.chromStart_y,hg38.knownCanonical.chromEnd_y,hg38.kgXref.geneSymbol,0,1,2
0,chr1,925800,925921,ENST00000342066.8,0,+,chr1,925730,944574,SAMD11,chr1,923928,944581
1,chr1,926013,930154,ENST00000342066.8,1,+,chr1,925730,944574,SAMD11,chr1,923928,944581
2,chr1,930336,931038,ENST00000342066.8,2,+,chr1,925730,944574,SAMD11,chr1,923928,944581
3,chr1,931089,935771,ENST00000342066.8,3,+,chr1,925730,944574,SAMD11,chr1,923928,944581
4,chr1,935896,939039,ENST00000342066.8,4,+,chr1,925730,944574,SAMD11,chr1,923928,944581

In [7]:
outdf.drop([0,1,2],inplace=True,axis=1)
outdf.head()

,#hg38.knownCanonical.chrom_x,hg38.knownCanonical.chromStart_x,hg38.knownCanonical.chromEnd_x,hg38.knownCanonical.transcript,transcriptno,direction,#hg38.knownCanonical.chrom_y,hg38.knownCanonical.chromStart_y,hg38.knownCanonical.chromEnd_y,hg38.kgXref.geneSymbol
0,chr1,925800,925921,ENST00000342066.8,0,+,chr1,925730,944574,SAMD11
1,chr1,926013,930154,ENST00000342066.8,1,+,chr1,925730,944574,SAMD11
2,chr1,930336,931038,ENST00000342066.8,2,+,chr1,925730,944574,SAMD11
3,chr1,931089,935771,ENST00000342066.8,3,+,chr1,925730,944574,SAMD11
4,chr1,935896,939039,ENST00000342066.8,4,+,chr1,925730,944574,SAMD11

In [8]:
genenames=list(set(outdf['hg38.kgXref.geneSymbol'].tolist()))
len(genenames)

18031

In [9]:
outdf=outdf.drop_duplicates(keep='first')

In [10]:
outdf[outdf.duplicated(subset=['#hg38.knownCanonical.chrom_x','hg38.knownCanonical.chromStart_x','hg38.knownCanonical.chromEnd_x','hg38.knownCanonical.transcript'], keep=False)]

Empty DataFrame
Columns: [#hg38.knownCanonical.chrom_x, hg38.knownCanonical.chromStart_x, hg38.knownCanonical.chromEnd_x, hg38.knownCanonical.transcript, transcriptno, direction, #hg38.knownCanonical.chrom_y, hg38.knownCanonical.chromStart_y, hg38.knownCanonical.chromEnd_y, hg38.kgXref.geneSymbol]
Index: []

In [11]:
outdf.to_csv(outfile,sep="\t",index=False)