In [1]:
import pandas as pd

infile="/Users/irffanalahi/Research/Research_update/Erin/test13ctref/onWB/datamanipulation/deconresult/cwref13ct_rcresults_healthywb_formatted_bcellfixed_CSxOut.txt"

columnlist=['CD4','CD8','CD19','CD56','Neu']

indf=pd.read_csv(infile,sep="\t",index_col=0)

indf.head()

,cB,CD4,CD8,iDC,M0,M1,M2,mDC,CD14,Neu,nB,CD56,PC,CD19,NK_cells,Neutrophils,Lymphocytes,T_cells,Monocytes
Mixture,,,,,,,,,,,,,,,,,,,
NU-41-Bulk-WB.bg,0.034408,0.180150,0.112013,0.149296,0.051780,0.051724,0.023551,0.195489,0.037383,0.284584,0.114081,0.094965,0.005109,0.148489,0.094965,0.284584,0.535617,0.292163,0.037383
NU-31-Bulk-WB.bg,0.049531,0.183273,0.125040,0.203636,0.111111,0.031818,0.031370,0.155172,0.034059,0.361809,0.067268,0.114724,0.014632,0.116799,0.114724,0.361809,0.539836,0.308313,0.034059
NU-46-Bulk-WB.bg,0.031394,0.109386,0.069557,0.266667,0.059289,0.241803,0.037817,0.199095,0.047339,0.671444,0.044562,0.058937,0.014539,0.075956,0.058937,0.671444,0.313837,0.178943,0.047339
NU-48-Bulk-WB.bg,0.055194,0.133263,0.095280,0.121581,0.155556,0.037190,0.030201,0.199052,0.049972,0.487293,0.046881,0.111583,0.028477,0.102075,0.111583,0.487293,0.442201,0.228543,0.049972
NU-14-Bulk-WB.bg,0.080521,0.181336,0.130423,0.162304,0.065217,0.028470,0.027002,0.167247,0.039257,0.340258,0.044929,0.114194,0.024442,0.125449,0.114194,0.340258,0.551404,0.311760,0.039257

In [2]:
indfsubsetted=(indf[columnlist]).copy()
indfsubsetted.head()

                       CD4       CD8      CD19      CD56       Neu
Mixture
NU-41-Bulk-WB.bg  0.180150  0.112013  0.148489  0.094965  0.284584
NU-31-Bulk-WB.bg  0.183273  0.125040  0.116799  0.114724  0.361809
NU-46-Bulk-WB.bg  0.109386  0.069557  0.075956  0.058937  0.671444
NU-48-Bulk-WB.bg  0.133263  0.095280  0.102075  0.111583  0.487293
NU-14-Bulk-WB.bg  0.181336  0.130423  0.125449  0.114194  0.340258

In [3]:
indfsubsetted=indfsubsetted.div(indfsubsetted.sum(axis=1), axis=0)
indfsubsetted['total'] = indfsubsetted.sum(axis=1)
indfsubsetted.head()

                       CD4       CD8      CD19      CD56       Neu  total
Mixture
NU-41-Bulk-WB.bg  0.219642  0.136567  0.181040  0.115783  0.346968    1.0
NU-31-Bulk-WB.bg  0.203265  0.138680  0.129540  0.127238  0.401277    1.0
NU-46-Bulk-WB.bg  0.111020  0.070597  0.077091  0.059818  0.681475    1.0
NU-48-Bulk-WB.bg  0.143372  0.102507  0.109818  0.120047  0.524256    1.0
NU-14-Bulk-WB.bg  0.203369  0.146270  0.140692  0.128069  0.381600    1.0

In [4]:
indfsubsetted.to_csv(infile+"_normalized.txt",sep="\t")