In [20]:
import numpy as np
import pandas as pd
import random as ran
import os

In [21]:
file_cn = 'mix_input_13CT_25mixes-1.txt'

transpose = False
header = 0
index_col= False

lower_lim = 0.1
upper_lim = 0.3

repetition = 5

mix_num = 25

outfol = 'cell_files_all_test'

In [22]:
if transpose:
    data_cn = pd.read_csv(file_cn, sep='\t', index_col=0, header=header)
else:
    data_cn = pd.read_csv(file_cn, sep='\t', header=header)

df_cn = pd.DataFrame(data_cn)

if transpose:
    df_cn = df_cn.T

df_cn.columns

Index(['PC', 'cB', 'mNeu', 'nB', 'NK', 'CD4', 'CD8', 'Mn', 'M0', 'M1', 'M2',
       'mDC', 'iDC'],
      dtype='object')

In [23]:
def generate_list(cell_name, cell_list, val):
    length = len(cell_list)
    vals = np.zeros(length)
    r = [ran.random() for i in range(1,length)]
    s = sum(r)
    r = [ (i/s) * (100 - val) for i in r ]
    name_seen = False
    for i in range(length):
        if cell_list[i] != cell_name:
            if name_seen == False:
                vals[i] = r[i]
            elif name_seen:
                vals[i] = r[i - 1]
        elif cell_list[i] == cell_name:
            vals[i] = val
            name_seen = True
    return vals

In [24]:
mixtures = np.linspace(lower_lim, upper_lim, num=mix_num) * 100
mixtures

array([10.        , 10.83333333, 11.66666667, 12.5       , 13.33333333,
       14.16666667, 15.        , 15.83333333, 16.66666667, 17.5       ,
       18.33333333, 19.16666667, 20.        , 20.83333333, 21.66666667,
       22.5       , 23.33333333, 24.16666667, 25.        , 25.83333333,
       26.66666667, 27.5       , 28.33333333, 29.16666667, 30.        ])

In [25]:
os.mkdir(outfol)
df_final = pd.DataFrame(columns = list(df_cn.columns))

In [26]:
# os.mkdir(outfol)

for cell in list(df_cn.columns):
    df_out = pd.DataFrame(columns = list(df_cn.columns))
    for val in mixtures:
        for i in range(repetition):
            arr = generate_list(cell, list(df_cn.columns), val)
            while 0.0 in arr:
                arr = generate_list(cell, list(df_cn.columns), val)
            df_out.loc[len(df_out.index)] = arr
    df_final = pd.concat([df_final, df_out])
    display(df_out)
    df_out.to_csv(outfol + '/' + cell + '.txt', sep='\t', index=False)

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,10.0,3.213657,8.626089,2.476967,7.707158,3.594102,11.437804,4.219170,6.417013,9.711993,8.721888,12.833559,11.040600
1,10.0,4.391462,12.379242,2.153592,7.473146,17.979412,7.156889,6.624536,2.779056,3.260681,9.675918,10.281009,5.845058
2,10.0,15.349871,1.591997,7.574789,9.130928,8.082332,5.422567,7.105884,8.948358,12.040218,2.143989,3.587117,9.021950
3,10.0,11.643342,11.106192,1.678794,7.538604,3.260711,4.901013,7.521934,3.900868,7.651736,12.507117,6.513990,11.775699
4,10.0,2.446979,9.870482,1.103792,12.211804,9.172759,12.105030,1.650781,0.959378,14.051466,5.425343,10.481753,10.520433
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,30.0,2.648731,4.831551,10.708878,1.877000,8.917055,10.221600,10.224548,4.860512,1.935035,4.857438,2.029499,6.888153
121,30.0,5.462116,4.124958,10.361577,1.340595,7.742310,8.471965,1.163862,9.094343,8.315582,4.739052,4.515503,4.668137
122,30.0,0.857882,9.459575,0.153343,1.431113,12.376496,3.391404,1.772749,11.335159,8.804378,8.211961,9.750729,2.455212
123,30.0,3.862619,6.632579,2.002909,9.997834,5.286773,2.950815,3.651536,7.614963,6.719680,10.196963,5.736933,5.346394
124,30.0,0.511065,13.625597,4.564183,6.663696,6.532604,9.922151,3.015809,2.376582,11.037964,2.375867,8.165548,1.208933

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,10.920592,10.0,6.389506,14.584965,3.242294,7.497877,5.781858,6.324040,4.019584,5.738568,12.666140,2.066329,10.768248
1,14.425475,10.0,7.384003,7.259310,0.105617,1.104566,4.110861,11.384296,15.277945,10.200894,2.794941,15.513419,0.438675
2,11.435392,10.0,6.624784,5.300917,5.473335,10.594849,9.834140,6.188831,7.057018,10.730619,7.913586,2.339683,6.506847
3,8.356487,10.0,4.252469,3.613350,1.291863,10.331784,6.852443,8.023809,6.086004,11.480153,12.515123,5.301438,11.895078
4,13.138259,10.0,0.946522,9.567936,14.188240,14.626560,5.162836,2.005088,2.836409,0.187135,4.583296,9.327371,13.430349
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,6.421480,30.0,1.765203,1.604582,0.998710,3.420375,8.947240,9.404467,5.099463,7.312726,4.710984,11.657920,8.656850
121,7.043792,30.0,5.578614,1.554767,7.151149,9.763973,8.365225,4.096345,3.190867,0.736590,4.688089,9.190942,8.639647
122,5.616939,30.0,11.557410,3.169097,7.188207,11.265091,8.397003,6.443001,6.890881,1.542487,0.933417,4.735541,2.260927
123,1.726942,30.0,5.498601,8.378782,9.974001,1.741851,6.926582,10.678148,4.024811,3.253933,3.092274,6.641378,8.062698
124,6.757596,30.0,0.104479,3.910231,12.367849,7.597592,1.990932,6.889027,12.098667,0.338646,3.123241,5.161348,9.660391

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,14.300182,3.920431,10.0,2.102065,2.938924,5.450721,8.426765,5.838995,12.438032,15.868354,2.862489,8.366719,7.486323
1,5.913396,15.270626,10.0,16.893294,10.871365,1.403344,4.744419,2.301342,2.516030,4.315355,0.224824,14.751007,10.794998
2,13.810589,12.959397,10.0,12.838829,1.105642,1.682716,9.173367,10.636657,0.303492,5.524863,11.502831,1.328844,9.132774
3,11.850414,3.526928,10.0,1.788952,10.466394,10.190873,16.740400,4.817288,0.899445,10.202674,10.300283,7.520695,1.695653
4,1.866210,4.626954,10.0,4.405236,9.921582,5.466824,14.251366,5.918625,11.795471,2.737888,9.446507,12.206067,7.357271
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,5.022853,11.364690,30.0,2.542597,7.215223,5.862281,1.457910,6.168211,7.199794,0.272394,3.604191,9.207281,10.082575
121,7.992187,1.706289,30.0,3.414300,7.024940,0.946865,8.042143,4.567129,13.225346,5.065077,7.149179,10.423025,0.443521
122,6.311896,1.187422,30.0,7.098848,8.677260,5.315968,8.979890,3.902447,5.620206,3.641221,8.180936,9.782242,1.301663
123,8.705892,1.835537,30.0,9.193794,8.200417,6.238358,4.351524,6.540087,5.483489,1.625637,6.318448,7.380592,4.126225
124,9.632190,13.764319,30.0,6.676623,1.645267,5.382106,3.059614,8.867312,11.672628,4.773148,0.743848,0.563452,3.219493

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,7.341790,3.237625,5.913213,10.0,14.481083,1.072108,8.318839,0.183525,7.105327,11.698128,11.236941,14.321327,5.090095
1,12.223337,11.804842,13.043631,10.0,7.531420,13.668004,8.906009,2.123282,1.695289,8.276629,0.977944,4.351296,5.398317
2,4.567032,2.205489,15.485735,10.0,0.614043,10.411106,16.109021,0.044717,8.839292,2.776306,6.510999,5.683504,16.752758
3,6.223459,6.493672,5.357803,10.0,9.153994,4.320985,7.391949,7.192682,4.703810,11.576444,11.510361,9.439578,6.635264
4,8.956592,12.699259,9.247957,10.0,8.750256,1.157560,5.329581,4.625600,8.821945,3.537343,11.916011,4.541361,10.416536
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,1.392079,13.155482,0.281357,30.0,7.136609,13.135155,11.325074,0.673106,3.859701,10.994237,1.151506,3.631338,3.264355
121,3.818821,5.952790,6.443889,30.0,0.026062,1.613135,9.064064,6.424503,8.331265,8.205070,8.898529,3.693779,7.528093
122,9.546661,6.084599,3.242452,30.0,5.455646,8.629166,0.149607,6.600189,4.561338,7.292548,9.720064,6.240594,2.477138
123,8.027414,0.039197,8.514521,30.0,4.353979,0.123196,8.134527,11.195202,7.497246,7.854963,6.390593,5.137302,2.731859
124,5.153813,10.009527,2.661363,30.0,7.812026,0.965202,5.469145,7.017458,7.023996,3.728343,9.706424,3.262277,7.190428

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,6.539922,7.137660,5.171608,2.836812,10.0,9.166222,9.703491,1.348636,9.710224,8.723167,11.149994,7.333939,11.178325
1,3.603842,0.562358,0.284186,12.971379,10.0,11.295788,5.799554,12.072535,8.915884,1.610309,8.613513,11.489764,12.780889
2,8.044385,13.118598,4.805910,4.986173,10.0,10.327311,3.680617,13.655508,12.213574,4.527822,8.484922,2.513642,3.641539
3,13.321588,2.179619,4.436652,6.915703,10.0,8.744022,7.847432,11.041057,4.324741,12.465676,13.134113,4.073260,1.516135
4,10.270872,10.035157,7.771383,10.859555,10.0,8.830620,6.848282,0.264994,4.403105,9.944981,8.413352,0.655914,11.701785
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,10.727479,5.308919,3.450566,11.279070,30.0,0.701774,0.162485,8.916400,5.491565,9.684003,6.206106,7.400363,0.671272
121,11.797943,7.554601,6.004971,10.745041,30.0,1.726546,2.852050,9.697155,1.320191,2.473322,3.853560,2.372357,9.602264
122,6.296096,0.632453,7.968806,5.225366,30.0,2.194530,5.240404,4.506437,4.553472,2.268614,9.009687,12.622992,9.481143
123,0.208753,8.625127,2.557785,6.664026,30.0,8.381843,7.443006,7.557902,5.630744,6.975397,4.958674,2.814285,8.182458
124,2.711051,10.266294,1.864337,11.046629,30.0,0.004639,8.923326,4.896225,1.132189,10.968087,1.421313,10.114385,6.651524

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,0.110201,7.407644,12.558348,3.488633,8.418930,10.0,5.495838,11.533493,9.466382,13.258631,1.716968,13.325301,3.219629
1,5.793913,6.821105,5.693415,9.556271,6.660165,10.0,8.974499,9.118708,7.208860,6.860573,4.768564,8.507105,10.036823
2,3.718571,8.717512,8.721210,10.341321,5.289794,10.0,9.466767,9.501206,4.222974,3.920405,5.665985,9.692484,10.741772
3,15.408190,7.143828,14.816480,0.326143,15.685638,10.0,3.460305,2.120882,1.226738,3.377222,11.511349,12.518150,2.405075
4,8.633005,10.150579,2.407748,10.519138,11.063202,10.0,6.254954,3.504863,9.126087,9.913123,10.675464,5.652600,2.099239
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,1.397638,7.469587,3.214493,1.101991,4.323968,30.0,12.536442,0.649100,5.997333,8.728855,2.455275,10.994907,11.130411
121,2.171967,11.255266,1.484076,4.965555,7.805122,30.0,11.386042,3.413300,7.254375,3.330315,9.436304,3.278892,4.218785
122,4.070649,5.884225,9.876811,6.274539,0.559821,30.0,1.438585,4.714217,5.297138,8.991797,7.867135,10.100727,4.924355
123,10.284095,0.176045,5.218045,3.837639,13.261178,30.0,3.170805,13.542276,10.849024,0.388425,6.504195,2.130686,0.637586
124,7.299526,0.887326,3.861480,6.622314,3.313051,30.0,2.878432,12.136302,12.527106,7.287927,7.716978,5.453451,0.016109

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,4.778716,6.060937,11.284294,10.766097,1.132417,5.762509,10.0,14.414590,10.428176,0.685871,5.035898,14.920419,4.730075
1,1.113467,10.642126,1.679621,8.421446,1.076947,16.579529,10.0,13.636087,5.504391,1.318561,16.290338,10.463514,3.273973
2,1.626415,12.972371,1.437452,10.492984,0.580295,10.176619,10.0,13.633498,3.798649,11.634112,9.035643,1.369814,13.242148
3,3.824664,12.400029,3.803160,3.599639,11.630381,3.639653,10.0,9.022667,7.157073,11.911122,7.586986,8.179268,7.245358
4,8.682386,5.143476,7.568233,11.023285,9.504767,0.470318,10.0,9.318685,10.567850,7.318644,5.833772,5.803026,8.765556
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,0.657341,9.150427,3.070451,5.228418,3.704065,8.958699,30.0,4.328097,7.250243,10.153007,6.723511,10.218452,0.557290
121,4.748877,12.400962,9.591888,4.340506,1.383596,14.900622,30.0,10.815141,5.468837,1.980696,2.786486,0.244105,1.338283
122,0.336643,10.091872,0.306561,1.872139,5.732045,6.489030,30.0,12.388893,0.904203,11.157648,14.882326,4.921778,0.916863
123,8.577174,3.905488,7.490687,6.547172,7.616629,2.995778,30.0,5.059338,4.828205,8.648331,4.410610,3.763659,6.156928
124,1.332449,5.051558,7.497035,5.775554,12.012778,2.246539,30.0,1.798343,10.564770,6.176772,9.515541,7.071060,0.957600

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,15.821897,6.670076,9.794323,15.886760,11.324188,2.418459,5.376337,10.0,1.992060,0.126863,11.286384,4.196233,5.106421
1,8.054781,1.603485,8.765079,9.716889,6.411013,11.973378,8.441131,10.0,7.162912,2.937245,11.340271,1.999068,11.594750
2,3.543877,2.964741,15.440762,2.445073,2.223061,11.840984,6.704134,10.0,3.506005,17.763043,3.892299,0.007275,19.668746
3,4.043923,4.752763,12.759418,14.592440,11.050936,5.843863,10.156599,10.0,6.871133,0.514744,3.829672,9.277377,6.307132
4,6.525714,12.358350,9.327068,7.412397,13.988791,2.483515,8.301584,10.0,3.386183,6.018122,4.349586,13.395417,2.453273
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,11.929794,7.332369,0.985098,10.997662,1.286315,4.953216,6.753279,30.0,3.834651,3.002447,3.088560,6.275994,9.560615
121,7.245685,5.196540,6.292421,7.955021,1.842069,7.794968,2.173013,30.0,9.917720,3.860128,5.534756,3.958711,8.228969
122,3.761388,9.410778,6.817119,4.742677,8.810818,6.586815,0.982120,30.0,9.764997,4.967065,5.019932,2.927481,6.208809
123,1.043086,1.592071,9.010290,2.125210,3.452166,0.838148,9.147845,30.0,11.341889,10.427620,12.241649,1.265150,7.514876
124,1.712997,9.407279,6.638697,1.520912,7.149083,4.916476,8.923803,30.0,6.395901,4.057508,2.277338,6.027021,10.972984

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,8.673268,10.315039,3.590891,1.468726,14.434508,5.558756,11.400731,2.639643,10.0,9.982675,12.436762,5.362423,4.136577
1,13.758674,6.051104,11.344611,8.939438,2.192073,9.636654,12.648444,1.995103,10.0,5.542156,8.424981,0.996493,8.470267
2,11.866618,8.474391,7.222404,0.369981,3.341817,10.071016,8.988800,5.100081,10.0,4.861161,11.248721,7.917730,10.537280
3,3.541103,9.892251,5.091188,10.805206,6.334266,4.293742,2.742795,9.057691,10.0,7.140989,10.740306,10.516874,9.843589
4,10.483482,6.809498,6.441226,12.129751,11.572790,7.671078,5.476351,9.116146,10.0,4.314712,4.831941,7.676623,3.476403
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,5.934416,3.195294,4.095562,3.732994,14.359678,7.212347,3.803718,0.437667,30.0,6.840466,10.041892,3.227004,7.118961
121,0.018487,2.040795,4.752369,9.040601,9.640513,8.499262,3.978793,0.642865,30.0,8.965426,3.859220,9.610066,8.951603
122,2.727473,8.541938,7.134622,4.322039,7.248859,11.653585,9.714617,2.934428,30.0,10.800961,0.384203,0.948330,3.588944
123,5.052033,5.065395,0.802348,7.856860,8.884246,8.957798,10.677885,4.514956,30.0,0.918887,8.712871,6.278334,2.278386
124,8.458929,1.008164,3.002666,7.654366,3.504157,5.923519,8.649141,6.158029,30.0,8.716404,6.200746,9.889626,0.834253

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,0.727136,13.064382,8.300372,9.424120,0.110176,8.436193,3.093476,11.098874,9.196542,10.0,10.479085,2.546641,13.523002
1,14.686932,0.688213,14.853995,1.778058,8.206275,7.448648,3.339947,7.966880,10.456824,10.0,1.630426,11.893212,7.050590
2,1.280216,4.140857,2.386869,6.847570,0.327328,3.057364,13.386304,8.067922,16.555240,10.0,15.566934,9.946972,8.436424
3,14.264889,2.291508,6.170886,4.615301,5.357974,2.627982,4.758827,9.863077,3.960086,10.0,15.211641,13.865009,7.012820
4,5.609503,10.415855,15.650377,7.880444,2.454462,16.004642,8.388197,1.428237,3.960286,10.0,1.002106,15.645073,1.560820
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,5.416493,0.716394,2.245612,3.773832,13.527669,6.222291,5.635658,0.828303,11.999317,30.0,7.596456,0.709522,11.328453
121,7.946570,6.215862,5.637385,1.074166,6.551074,5.420524,2.957062,9.200358,2.534462,30.0,4.265398,9.064673,9.132466
122,2.964125,3.213934,7.262209,10.494967,6.549164,7.707839,0.292123,8.207294,1.355061,30.0,6.709190,10.920076,4.324017
123,9.594740,0.111483,8.685806,1.027065,7.267394,2.890091,7.341454,1.387771,11.392859,30.0,7.843923,0.108132,12.349282
124,2.101063,5.310695,10.494861,0.096088,9.967083,6.920283,10.840868,8.326453,7.359746,30.0,6.514374,1.568284,0.500203

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,15.427575,1.360429,10.581841,13.374679,6.532304,9.101684,4.220363,6.895244,14.001718,1.288836,10.0,2.048401,5.166926
1,11.782695,7.036169,10.306742,12.179881,6.101935,2.349297,6.914051,0.356486,12.955508,4.467062,10.0,7.498263,8.051910
2,4.443547,17.803358,0.351618,6.119267,16.000886,3.437858,9.134782,1.440092,1.543284,12.416061,10.0,4.776411,12.532837
3,6.333415,2.417554,12.517371,13.028500,0.475237,10.381207,0.060878,5.167020,10.970579,12.417389,10.0,8.317151,7.913698
4,9.760666,10.192366,11.278672,3.218246,11.851316,9.208032,1.325373,11.142860,5.457325,2.092124,10.0,7.158763,7.314256
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,2.021671,3.132781,11.527902,2.076437,6.522645,9.530748,9.300869,4.394161,2.927504,1.540729,30.0,9.081883,7.942669
121,6.198444,5.592453,5.590888,2.040710,2.327965,12.997805,0.173125,5.823763,2.526983,9.085712,30.0,9.283521,8.358631
122,6.771625,5.609308,9.172904,7.510157,9.733566,10.356347,2.589879,3.196975,0.912522,10.910683,30.0,0.823497,2.412536
123,4.700411,9.950833,4.706722,7.855164,9.517261,1.935758,5.563572,8.224667,0.001904,9.661978,30.0,7.313622,0.568107
124,6.239758,2.934976,9.186845,6.962261,5.411478,10.177848,11.365177,0.418255,7.435976,4.184706,30.0,5.524680,0.158040

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,9.557103,11.380306,7.196423,4.961622,7.975795,8.821052,2.035377,10.419037,3.706019,0.195499,11.756641,10.0,11.995125
1,8.290980,2.999358,3.267660,13.132381,1.918311,5.840126,4.542469,13.442099,7.530004,15.232805,2.217303,10.0,11.586503
2,4.885876,13.979848,12.204938,0.696812,16.696403,1.397287,16.434604,1.947484,0.763782,4.375722,6.725215,10.0,9.892029
3,0.918375,9.456701,11.355485,4.512288,7.853923,12.287829,12.028631,0.910664,1.919889,12.610998,4.737206,10.0,11.408010
4,15.469425,6.923600,10.424772,1.600593,6.100124,9.821011,2.068748,7.542426,15.371966,2.281614,1.077152,10.0,11.318569
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,0.729832,7.898331,7.502743,1.449093,6.435478,9.840006,7.979913,10.291275,5.852528,8.634489,0.541469,30.0,2.844845
121,2.105828,10.927141,7.880446,10.999179,7.845598,1.455716,4.127242,11.130005,5.488334,6.751640,1.093677,30.0,0.195193
122,8.891951,5.821186,7.998881,4.327193,5.240512,3.636608,4.352332,3.912038,2.630108,0.596267,11.273427,30.0,11.319496
123,9.124184,7.410990,5.187806,8.960504,3.956526,9.123756,9.082034,0.902924,0.019149,5.260608,8.747457,30.0,2.224062
124,7.060506,7.910445,9.078750,0.024885,1.984405,2.052801,1.838059,7.755169,5.011747,5.428493,10.448285,30.0,11.406454

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,15.874017,0.459361,1.511838,13.072535,4.540588,1.562970,13.097197,8.849524,7.041171,10.916301,3.754787,9.319710,10.0
1,7.148070,0.291647,7.481411,4.138405,11.370853,9.656330,10.417563,11.970823,6.391596,8.211600,7.000967,5.920735,10.0
2,5.345829,1.828946,11.645168,8.882482,0.948985,9.131894,10.211288,9.287374,10.360251,5.779800,3.650922,12.927061,10.0
3,6.625273,10.428309,3.623246,8.690460,5.696703,11.860459,7.630228,12.051594,1.722338,4.713075,10.697463,6.260852,10.0
4,6.547420,10.078257,5.862973,7.056529,5.385511,16.978775,7.437259,0.881606,7.354819,8.962504,6.720431,6.733916,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,7.489452,8.995335,2.912171,9.632652,3.700795,4.589507,4.846950,4.485251,6.113907,4.489559,5.390679,7.353742,30.0
121,7.074148,9.894343,7.898984,4.357422,1.030979,3.844563,6.364740,7.033821,1.932364,9.049374,6.806030,4.713232,30.0
122,9.805064,1.251530,1.381752,1.911091,1.525501,9.220538,9.697241,9.598794,9.390210,1.877282,5.197749,9.143248,30.0
123,3.998801,8.581420,4.916289,4.810161,8.872572,2.249815,2.337133,11.935305,1.095668,11.854605,1.599909,7.748322,30.0
124,7.229821,1.787616,17.120184,5.174930,9.416796,7.520441,0.982919,6.886485,2.031541,2.161439,7.222842,2.464987,30.0

In [27]:
df_final

,PC,cB,mNeu,nB,NK,CD4,CD8,Mn,M0,M1,M2,mDC,iDC
0,10.000000,3.213657,8.626089,2.476967,7.707158,3.594102,11.437804,4.219170,6.417013,9.711993,8.721888,12.833559,11.040600
1,10.000000,4.391462,12.379242,2.153592,7.473146,17.979412,7.156889,6.624536,2.779056,3.260681,9.675918,10.281009,5.845058
2,10.000000,15.349871,1.591997,7.574789,9.130928,8.082332,5.422567,7.105884,8.948358,12.040218,2.143989,3.587117,9.021950
3,10.000000,11.643342,11.106192,1.678794,7.538604,3.260711,4.901013,7.521934,3.900868,7.651736,12.507117,6.513990,11.775699
4,10.000000,2.446979,9.870482,1.103792,12.211804,9.172759,12.105030,1.650781,0.959378,14.051466,5.425343,10.481753,10.520433
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,7.489452,8.995335,2.912171,9.632652,3.700795,4.589507,4.846950,4.485251,6.113907,4.489559,5.390679,7.353742,30.000000
121,7.074148,9.894343,7.898984,4.357422,1.030979,3.844563,6.364740,7.033821,1.932364,9.049374,6.806030,4.713232,30.000000
122,9.805064,1.251530,1.381752,1.911091,1.525501,9.220538,9.697241,9.598794,9.390210,1.877282,5.197749,9.143248,30.000000
123,3.998801,8.581420,4.916289,4.810161,8.872572,2.249815,2.337133,11.935305,1.095668,11.854605,1.599909,7.748322,30.000000
124,7.229821,1.787616,17.120184,5.174930,9.416796,7.520441,0.982919,6.886485,2.031541,2.161439,7.222842,2.464987,30.000000

In [28]:
df_final.to_csv(outfol + '/combined.txt', sep='\t', index=False)