In [1]:
import pandas as pd
ingenefile="/Users/irffanalahi/Research/Research_update/SM/melcfdref/LargerLTME/BluOurPBL/Dashboard/BlOurPBLourCD8TIL_out_mincpg2_q0.5_addedcol_q0.00001_diff0.1_hypo_noheader_genomic_feature_withrepeat_header_celltypeseperated/develop/CD8TIL_row_combined.txt"
outfile=ingenefile+"_prioritizedregion.txt"
priority_list=['promoter','cds','3utrexon','5utrexon','intron','repeat']

ingenedf=pd.read_csv(ingenefile,sep="\t")

ingenedf.head()

,chrom,start,end,q,diff,#cpg,p(MWU),p(2dks),CD8TIL,others,...,29,30,31,32,33,34,35,36,Gene/Repeat type,Region
0,chr1,973577,973714,0.000005,-0.509535,6,7.765300e-11,5.848000e-09,0.3295,0.83903,...,-0.552111,-0.322917,-0.335889,-0.322917,-0.596556,chr1,973499,973640,PLEKHN1,cds
1,chr1,973577,973714,0.000005,-0.509535,6,7.765300e-11,5.848000e-09,0.3295,0.83903,...,-0.552111,-0.322917,-0.335889,-0.322917,-0.596556,chr1,973499,973640,PLEKHN1,cds
2,chr1,973577,973714,0.000005,-0.509535,6,7.765300e-11,5.848000e-09,0.3295,0.83903,...,-0.552111,-0.322917,-0.335889,-0.322917,-0.596556,chr1,973499,973640,PLEKHN1,cds
3,chr1,973577,973714,0.000005,-0.509535,6,7.765300e-11,5.848000e-09,0.3295,0.83903,...,-0.552111,-0.322917,-0.335889,-0.322917,-0.596556,chr1,973499,973640,PLEKHN1,cds
4,chr1,973577,973714,0.000005,-0.509535,6,7.765300e-11,5.848000e-09,0.3295,0.83903,...,-0.552111,-0.322917,-0.335889,-0.322917,-0.596556,chr1,973499,973640,PLEKHN1,cds

In [2]:
grouped=ingenedf.groupby(['chrom','start','end'])
rowlist=[]
for name, group in grouped:
    for region in priority_list:
        tmp= group[group['Region']==region]
        if tmp.shape[0]>0:
            tmprow=tmp.iloc[0]
            if tmprow['Region']=='3utrexon' or tmprow=='5utrexon':
                tmprow['Region']=='3/5 utrexon'
                
            rowlist.append(tmp.iloc[0])  ##### hadle 2utr/5ut
            break

In [4]:
outdf=pd.DataFrame(rowlist)
outdf.to_csv(outfile,sep="\t",index=False)