In [1]:
###worksfor hypo only as calculated for 'confidence' 

import pandas as pd
from statistics import mean
import time
import numpy as np
from collections import defaultdict
import sys

start_time = time.time()


smfile='/Users/irffanalahi/Research/Research_code/gitignorefolder/MHB_per_read/softreadcounting/testtheidea/try2/BL14_all_matrixCin_nr0.4_imputed_rowmean.txt_bg_intesectedwith_CD4DMRofBL14atleast.2SM_g1_CD4_3_g2_others_33_addedcol.txt'
finalfile='/Users/irffanalahi/Research/Research_code/gitignorefolder/MHB_per_read/softreadcounting/testtheidea/try2/CD4allrange_NR_1000000_insilmix60_sorted_howsm_single_mode_pp_masterdf.txt_rej-99999.0_mincpg1_rejmode_nov_final_test.txt'
smdf=pd.read_csv(smfile,sep="\t",index_col=['chrom','start','end'])
finaldf=pd.read_csv(finalfile,sep="\t")
celltype='CD4'
deltagreaterforpositive=0  ##############>0

allct=['CD4','CD8','nB','NK','Mn','mNeu','m8','DC','Eo','Tr','m4','Mg','Er','mB']

smdf.head()

                              CD4       CD8        nB        NK        Mn  \
chrom start    end
chr1  32387132 32387134  0.214333  0.507000  0.992000  0.968333  0.968667
      32387376 32387378  0.127000  0.633000  0.946667  0.881333  1.000000
      32387403 32387405  0.136667  0.869333  0.958333  0.948667  1.000000
      32387409 32387411  0.182333  0.969667  0.989667  0.990667  0.982333
      32387417 32387419  0.666667  0.957333  0.980333  0.956333  1.000000

                             mNeu      m8        DC      Eo      Tr  ...  \
chrom start    end                                                   ...
chr1  32387132 32387134  0.965667  0.9420  0.981000  0.9585  0.8695  ...
      32387376 32387378  0.860000  0.8300  0.928000  0.7750  0.6930  ...
      32387403 32387405  0.953667  0.8635  1.000000  0.9690  0.7770  ...
      32387409 32387411  0.957333  0.9900  1.000000  1.0000  0.7570  ...
      32387417 32387419  0.912667  1.0000  0.981333  0.9665  0.9300  ...

                           CD4-m8    CD4-DC    CD4-Eo    CD4-Tr    CD4-m4  \
chrom start    end
chr1  32387132 32387134 -0.727667 -0.766667 -0.744167 -0.655167 -0.705667
      32387376 32387378 -0.703000 -0.801000 -0.648000 -0.566000 -0.609000
      32387403 32387405 -0.726833 -0.863333 -0.832333 -0.640333 -0.574833
      32387409 32387411 -0.807667 -0.817667 -0.817667 -0.574667 -0.565667
      32387417 32387419 -0.333333 -0.314667 -0.299833 -0.263333 -0.243833

                           CD4-Mg    CD4-Er    CD4-mB  \
chrom start    end
chr1  32387132 32387134 -0.785667 -0.707667 -0.771667
      32387376 32387378 -0.771500 -0.767500 -0.768667
      32387403 32387405 -0.798833 -0.850333 -0.848000
      32387409 32387411 -0.796167 -0.805667 -0.771333
      32387417 32387419 -0.296333 -0.311333 -0.301333

                         maxCompartmentwisedelta  minCompartmentwiseDelta
chrom start    end
chr1  32387132 32387134                -0.292667                -0.785667
      32387376 32387378                -0.506000                -0.873000
      32387403 32387405                -0.574833                -0.863333
      32387409 32387411                -0.565667                -0.817667
      32387417 32387419                -0.243833                -0.333333

[5 rows x 33 columns]

In [2]:
set(finaldf['finalrejectedfor'].tolist())

{'notdetermined'}

In [3]:
finaldf=finaldf[(finaldf['finalacceptedfor']==celltype) | (finaldf['finalrejectedfor'].str.contains(celltype))]

In [4]:
preveresult=finaldf[finaldf['finalacceptedfor']==celltype].shape[0]/finaldf.shape[0]
preveresult

1.0

In [5]:
finaldf.shape

(1, 20)

In [6]:
finaldf.to_csv(finalfile+"_informative.txt",sep="\t",index=False)

In [7]:
finaldf.head()

,ReadName,allcelltype,ucelltype,assignedcelltype,CheckedCpG,mismatchCpG,notacceptedCpG,acceptedCpG,finalacceptedfor,finalrejectedfor,MateCIGARok,hypolist,len_hypolist,hyperlist,len_hyperlist,allnotmatched,len_allnotmatched,fraglength,intersection_ofhypohyper,len_intersection_ofhypohyper
0,CD4.HWI-ST1450_140:1:2312:17535:63541#12,"['CD4', 'CD4', 'CD4', 'CD4', 'CD4', 'CD4', 'CD...",['CD4'],CD4,"['chr1:32387403', 'chr1:32387409', 'chr1:32387...",[''],['chr1:32387489'],"['chr1:32387403', 'chr1:32387409', 'chr1:32387...",CD4,notdetermined,Y,"['chr1:32387403', 'chr1:32387409', 'chr1:32387...",8,['chr1:32387489'],1,[],0,0,[],0

In [8]:
finaldf['acceptedCpG']=finaldf.acceptedCpG.apply(lambda x: x[1:-1].split(','))
finaldf['notacceptedCpG']=finaldf.notacceptedCpG.apply(lambda x: x[1:-1].split(','))
finaldf['mismatchCpG']=finaldf.mismatchCpG.apply(lambda x: x[1:-1].split(','))

In [9]:





finaldf['#CpG']=-1

finaldf['deltabasedfragassignment']='NotAssigned'

In [10]:
for ct in allct:
    finaldf[ct]='NotAssigned'
    #finaldf[ct+"_CW"]='NotAssigned'
finaldf.head()

,ReadName,allcelltype,ucelltype,assignedcelltype,CheckedCpG,mismatchCpG,notacceptedCpG,acceptedCpG,finalacceptedfor,finalrejectedfor,...,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,CD4.HWI-ST1450_140:1:2312:17535:63541#12,"['CD4', 'CD4', 'CD4', 'CD4', 'CD4', 'CD4', 'CD...",['CD4'],CD4,"['chr1:32387403', 'chr1:32387409', 'chr1:32387...",[''],['chr1:32387489'],"['chr1:32387403', 'chr1:32387409', 'chr1:323...",CD4,notdetermined,...,NotAssigned,NotAssigned,NotAssigned,NotAssigned,NotAssigned,NotAssigned,NotAssigned,NotAssigned,NotAssigned,NotAssigned

In [11]:
def processrowhelper(cpglist_fromprocessrow):
    
    indexlist=[]
    for cpg in cpglist_fromprocessrow:
        if not eval(cpg):
            continue
        
        chrom,start=eval(cpg).split(':')
        indexlist.append((chrom,int(start),int(start)+2))
    
     

    
    return indexlist


    
def deltacalculation(cpgsfordelta):
    
    ctwiseScore = defaultdict(list)
    for ct in allct:
        if ct==celltype:
            
           
            ctwiseScore[ct].append((cpgsfordelta.mean(axis=1)).sum())
           

        else:
            
    
            celltyperelatedcol=celltype+'-'+ct
            othercol=cpgsfordelta.columns.tolist()
            othercol.remove(celltyperelatedcol)
            
            otherctdf=cpgsfordelta[othercol]
            
            currentctdf=(cpgsfordelta[celltyperelatedcol]).to_frame(name=celltyperelatedcol)
            
            
  
            
            temp=otherctdf-currentctdf.values
            
            
            
            tempsum=(temp.mean(axis=1)).sum()
         
            
            ctwiseScore[ct].append(tempsum)
            
            
    ctwisescoredf=pd.DataFrame(ctwiseScore)
    return ctwisescoredf
        


def processrow(aindex,arow):
   
    notacceptedCpGList=arow['notacceptedCpG']
    acceptedCpGList=arow['acceptedCpG']
    
    
    
    
    accindex=processrowhelper(acceptedCpGList)
    
    
    ACCscore=pd.DataFrame(0,index=[0],columns=allct)
    
    
    
    if len(accindex)>0:
        corresACCcpgs=(smdf.loc[accindex])*-1 
        ACCscore=deltacalculation(corresACCcpgs)
    

  
    
    rejindex=processrowhelper(notacceptedCpGList)
    
    REJscore=pd.DataFrame(0,index=[0],columns=allct)
    
    
    
    if len(rejindex)>0:
        corresREJcpgs=smdf.loc[rejindex]
        
        REJscore=deltacalculation(corresREJcpgs)
    

    
    finalscore=ACCscore+REJscore
    if finalscore.shape[0]!=1:
        print('something wrong')
        sys.exit(1)
    
    finaldf.loc[index,allct]=finalscore.iloc[0]
 
    
    totalcpgs=len(accindex)+len(rejindex)
    
    finaldf.loc[index,'#CpG']=totalcpgs

In [12]:
smdfcols=smdf.columns.tolist()
smdf=smdf[smdfcols[smdfcols.index('DMRname')+1:smdfcols.index('maxCompartmentwisedelta')]]
smdf.head()

                          CD4-CD8    CD4-nB    CD4-NK    CD4-Mn  CD4-mNeu  \
chrom start    end
chr1  32387132 32387134 -0.292667 -0.777667 -0.754000 -0.754333 -0.751333
      32387376 32387378 -0.506000 -0.819667 -0.754333 -0.873000 -0.733000
      32387403 32387405 -0.732667 -0.821667 -0.812000 -0.863333 -0.817000
      32387409 32387411 -0.787333 -0.807333 -0.808333 -0.800000 -0.775000
      32387417 32387419 -0.290667 -0.313667 -0.289667 -0.333333 -0.246000

                           CD4-m8    CD4-DC    CD4-Eo    CD4-Tr    CD4-m4  \
chrom start    end
chr1  32387132 32387134 -0.727667 -0.766667 -0.744167 -0.655167 -0.705667
      32387376 32387378 -0.703000 -0.801000 -0.648000 -0.566000 -0.609000
      32387403 32387405 -0.726833 -0.863333 -0.832333 -0.640333 -0.574833
      32387409 32387411 -0.807667 -0.817667 -0.817667 -0.574667 -0.565667
      32387417 32387419 -0.333333 -0.314667 -0.299833 -0.263333 -0.243833

                           CD4-Mg    CD4-Er    CD4-mB
chrom start    end
chr1  32387132 32387134 -0.785667 -0.707667 -0.771667
      32387376 32387378 -0.771500 -0.767500 -0.768667
      32387403 32387405 -0.798833 -0.850333 -0.848000
      32387409 32387411 -0.796167 -0.805667 -0.771333
      32387417 32387419 -0.296333 -0.311333 -0.301333

In [13]:
for index, row in finaldf.iterrows():
    

    processrow(index, row)

In [14]:
finaldf['maxscoredCT']=(finaldf[allct].astype(float)).idxmax(axis=1)
finaldf.head()

,ReadName,allcelltype,ucelltype,assignedcelltype,CheckedCpG,mismatchCpG,notacceptedCpG,acceptedCpG,finalacceptedfor,finalrejectedfor,...,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB,maxscoredCT
0,CD4.HWI-ST1450_140:1:2312:17535:63541#12,"['CD4', 'CD4', 'CD4', 'CD4', 'CD4', 'CD4', 'CD...",['CD4'],CD4,"['chr1:32387403', 'chr1:32387409', 'chr1:32387...",[''],['chr1:32387489'],"['chr1:32387403', 'chr1:32387409', 'chr1:323...",CD4,notdetermined,...,-0.0120972,-0.0776389,-0.350819,-0.151306,0.650903,1.31824,-0.124764,-0.252056,-0.228042,CD4

In [15]:
finaldf.to_csv(finalfile+"_softRD.txt",sep="\t",index=False)

In [16]:
finaldf=finaldf[finaldf['#CpG']>0]

finaldf.loc[finaldf[celltype]>deltagreaterforpositive,'deltabasedfragassignment']=finaldf.loc[finaldf[celltype]>deltagreaterforpositive,'maxscoredCT']

finaldf.loc[finaldf[celltype]<=deltagreaterforpositive,'deltabasedfragassignment']='Rejeceted'+'_'+celltype

In [17]:
allacceptedDelta=finaldf.loc[finaldf['deltabasedfragassignment']==celltype,celltype].sum()
rejectedalldelta=finaldf.loc[finaldf['deltabasedfragassignment']=='Rejeceted'+'_'+celltype,celltype].sum()
deltabasedresult=allacceptedDelta/(allacceptedDelta+abs(rejectedalldelta))

In [18]:
allaccfrag=finaldf[finaldf['deltabasedfragassignment']==celltype].shape[0]
allrejfrag=finaldf[finaldf['deltabasedfragassignment']=='Rejeceted'+'_'+celltype].shape[0]
fragresult=allaccfrag/(allaccfrag+allrejfrag)

In [19]:
allacccpgnumber=finaldf.loc[finaldf['deltabasedfragassignment']==celltype,"#CpG"].sum()
allREJcpgnumber=finaldf.loc[finaldf['deltabasedfragassignment']=='Rejeceted'+'_'+celltype,"#CpG"].sum()

cpgweightedresult=allacccpgnumber/(allacccpgnumber+allREJcpgnumber)

In [20]:
deltaweightedbycpgResult=allacceptedDelta/(allacccpgnumber+allREJcpgnumber)

In [21]:
resultdf=pd.DataFrame({'deltabasedresult':[deltabasedresult],'deltaweightedbycpgResult':[deltaweightedbycpgResult],'fragresult':[fragresult],'cpgweightedFRAGresult':cpgweightedresult})
resultdf.to_csv(finalfile+"_softRD_result.txt",sep="\t",index=False)

In [22]:
finaldf.to_csv(finalfile+"_softRDnozeroCpG.txt",sep="\t",index=False)

end_time = time.time()

time_elapsed = (end_time - start_time)

print(time_elapsed)

0.3931701183319092