In [1]:
import pandas as pd
largeSMfile = '/Users/irffanalahi/Research/Research_update/SoftRD/hashtable_stats/tieredApproach/rankspace_idea/inflection_point/Blige/rankedCT_fol/rankedCT_SM_top1000_SM_unique'

infofile='/Users/irffanalahi/Research/Research_update/SoftRD/hashtable_stats/tieredApproach/rankspace_idea/inflection_point/Blige/rankedCT_fol/rankedCT_index.txt'

largesmdf=pd.read_csv(largeSMfile,sep='\t',index_col=['chrom','start'])
largesmdf.head()

                NaiveCD4-others  NaiveCD8-others  nB-others  NK-others  \
chrom start
chr2  26275496              0.9              0.9        0.9        0.9
      26275555              0.9              0.9        0.9        0.9
chr7  44252119              0.9              0.9        0.9        0.9
chr17 58309346              0.9              0.9        0.9        0.9
      57096997              0.9              0.9        0.9        0.9

                PC-others  Mono-others  M0-others  M1-others  M2-others  \
chrom start
chr2  26275496        0.9          0.9        0.9        0.9  -0.855634
      26275555        0.9          0.9        0.9        0.9  -0.798746
chr7  44252119        0.9          0.9        0.9        0.9  -0.773179
chr17 58309346        0.9          0.9        0.9        0.9  -0.820279
      57096997        0.9          0.9        0.9        0.9  -0.829185

                iDC-others  ...  cm8-others  em8-others  Eo-others  \
chrom start                 ...
chr2  26275496         0.9  ...         0.9         0.9        0.9
      26275555         0.9  ...         0.9         0.9        0.9
chr7  44252119         0.9  ...         0.9         0.9        0.9
chr17 58309346         0.9  ...         0.9         0.9        0.9
      57096997         0.9  ...         0.9         0.9        0.9

                Tregs-others  em4-others  ed8-others  Mg-others  cm4-others  \
chrom start
chr2  26275496           0.9         0.9         0.9        0.9         0.9
      26275555           0.9         0.9         0.9        0.9         0.9
chr7  44252119           0.9         0.9         0.9        0.9         0.9
chr17 58309346           0.9         0.9         0.9        0.9         0.9
      57096997           0.9         0.9         0.9        0.9         0.9

                Er-others  mB-others
chrom start
chr2  26275496        0.9        0.9
      26275555        0.9        0.9
chr7  44252119        0.9        0.9
chr17 58309346        0.9        0.9
      57096997        0.9        0.9

[5 rows x 22 columns]

In [2]:
largesmdf['mincolname']=largesmdf.idxmin(axis=1)
largesmdf.head()

                NaiveCD4-others  NaiveCD8-others  nB-others  NK-others  \
chrom start
chr2  26275496              0.9              0.9        0.9        0.9
      26275555              0.9              0.9        0.9        0.9
chr7  44252119              0.9              0.9        0.9        0.9
chr17 58309346              0.9              0.9        0.9        0.9
      57096997              0.9              0.9        0.9        0.9

                PC-others  Mono-others  M0-others  M1-others  M2-others  \
chrom start
chr2  26275496        0.9          0.9        0.9        0.9  -0.855634
      26275555        0.9          0.9        0.9        0.9  -0.798746
chr7  44252119        0.9          0.9        0.9        0.9  -0.773179
chr17 58309346        0.9          0.9        0.9        0.9  -0.820279
      57096997        0.9          0.9        0.9        0.9  -0.829185

                iDC-others  ...  em8-others  Eo-others  Tregs-others  \
chrom start                 ...
chr2  26275496         0.9  ...         0.9        0.9           0.9
      26275555         0.9  ...         0.9        0.9           0.9
chr7  44252119         0.9  ...         0.9        0.9           0.9
chr17 58309346         0.9  ...         0.9        0.9           0.9
      57096997         0.9  ...         0.9        0.9           0.9

                em4-others  ed8-others  Mg-others  cm4-others  Er-others  \
chrom start
chr2  26275496         0.9         0.9        0.9         0.9        0.9
      26275555         0.9         0.9        0.9         0.9        0.9
chr7  44252119         0.9         0.9        0.9         0.9        0.9
chr17 58309346         0.9         0.9        0.9         0.9        0.9
      57096997         0.9         0.9        0.9         0.9        0.9

                mB-others  mincolname
chrom start
chr2  26275496        0.9   M2-others
      26275555        0.9   M2-others
chr7  44252119        0.9   M2-others
chr17 58309346        0.9   M2-others
      57096997        0.9   M2-others

[5 rows x 23 columns]

In [3]:
infodf=pd.read_csv(infofile,sep='\t')
#infodf['Unnamed: 0']
infodf.head()

  Unnamed: 0  Index
0         M2    214
1   NaiveCD8    599
2        em4    599
3         M0    125
4   NaiveCD4    745

In [4]:
grouped=largesmdf.groupby('mincolname')
outlist=[]
for name, group in grouped:
   
    tempct=name.replace('-others','')
    corresnumber=(infodf[infodf['Unnamed: 0']==tempct]['Index']).tolist()[0]
   
    tempdf=group.head(n=corresnumber+1)
    
    outlist.append(tempdf)

In [5]:
outdf=pd.concat(outlist)
outdf=outdf.drop(['mincolname'],axis=1)

In [6]:
outdf.to_csv(infofile+"_inflectionSM.txt",sep='\t')