In [1]:
import pandas as pd
infile="/Users/irffanalahi/Research/Research_update/SoftRD/hashtable_stats/BL14_all_matrixCin_nr0.4_imputed_rowmean.txt_bg_othermean_backup.txt"

outfile=infile

scorecolumns=['CD4-others','CD8-others','nB-others','NK-others','Mn-others','mNeu-others','m8-others','DC-others','Eo-others','Tr-others','m4-others','Mg-others','Er-others','mB-others']

indf=pd.read_csv(infile,sep="\t")
indf.head()

,position,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,...,Mn-others,mNeu-others,m8-others,DC-others,Eo-others,Tr-others,m4-others,Mg-others,Er-others,mB-others
0,chr1:16138,0.879333,0.870667,0.954667,0.935667,0.918667,0.785000,0.8690,0.948000,0.9200,...,0.014423,-0.129526,-0.039064,0.046013,0.015859,-0.024526,0.056244,0.034167,-0.032064,0.037756
1,chr1:16242,0.654000,0.641667,0.765667,0.697667,0.743333,0.569667,0.6395,0.660333,0.6400,...,0.109038,-0.077987,-0.002782,0.019654,-0.002244,0.083910,-0.038321,-0.037244,-0.101321,-0.158038
2,chr1:16633,0.948667,1.000000,0.875000,0.884333,1.000000,0.741000,0.8750,0.889000,0.7335,...,0.102013,-0.176910,-0.032603,-0.017526,-0.184987,0.102013,0.102013,0.102013,0.102013,-0.191628
3,chr1:16645,0.980333,0.972333,0.966667,0.946333,1.000000,0.958333,1.0000,0.958333,1.0000,...,0.024756,-0.020115,0.024756,-0.020115,0.024756,0.024756,0.024756,-0.016705,0.024756,-0.045962
4,chr1:16664,0.984000,0.963000,1.000000,0.942000,1.000000,1.000000,1.0000,0.889000,0.9720,...,0.035603,0.035603,0.035603,-0.083936,0.005449,0.035603,-0.018244,-0.013397,-0.018244,-0.036910

In [2]:
indf[['chrom','start']] = indf.position.str.split(':',expand=True)
indf['start'] = indf['start'].astype(int)

In [3]:
indf.head()

,position,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,...,m8-others,DC-others,Eo-others,Tr-others,m4-others,Mg-others,Er-others,mB-others,chrom,start
0,chr1:16138,0.879333,0.870667,0.954667,0.935667,0.918667,0.785000,0.8690,0.948000,0.9200,...,-0.039064,0.046013,0.015859,-0.024526,0.056244,0.034167,-0.032064,0.037756,chr1,16138
1,chr1:16242,0.654000,0.641667,0.765667,0.697667,0.743333,0.569667,0.6395,0.660333,0.6400,...,-0.002782,0.019654,-0.002244,0.083910,-0.038321,-0.037244,-0.101321,-0.158038,chr1,16242
2,chr1:16633,0.948667,1.000000,0.875000,0.884333,1.000000,0.741000,0.8750,0.889000,0.7335,...,-0.032603,-0.017526,-0.184987,0.102013,0.102013,0.102013,0.102013,-0.191628,chr1,16633
3,chr1:16645,0.980333,0.972333,0.966667,0.946333,1.000000,0.958333,1.0000,0.958333,1.0000,...,0.024756,-0.020115,0.024756,0.024756,0.024756,-0.016705,0.024756,-0.045962,chr1,16645
4,chr1:16664,0.984000,0.963000,1.000000,0.942000,1.000000,1.000000,1.0000,0.889000,0.9720,...,0.035603,-0.083936,0.005449,0.035603,-0.018244,-0.013397,-0.018244,-0.036910,chr1,16664

In [4]:
indf['end']=indf['start']+2
indf.head()

,position,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,...,DC-others,Eo-others,Tr-others,m4-others,Mg-others,Er-others,mB-others,chrom,start,end
0,chr1:16138,0.879333,0.870667,0.954667,0.935667,0.918667,0.785000,0.8690,0.948000,0.9200,...,0.046013,0.015859,-0.024526,0.056244,0.034167,-0.032064,0.037756,chr1,16138,16140
1,chr1:16242,0.654000,0.641667,0.765667,0.697667,0.743333,0.569667,0.6395,0.660333,0.6400,...,0.019654,-0.002244,0.083910,-0.038321,-0.037244,-0.101321,-0.158038,chr1,16242,16244
2,chr1:16633,0.948667,1.000000,0.875000,0.884333,1.000000,0.741000,0.8750,0.889000,0.7335,...,-0.017526,-0.184987,0.102013,0.102013,0.102013,0.102013,-0.191628,chr1,16633,16635
3,chr1:16645,0.980333,0.972333,0.966667,0.946333,1.000000,0.958333,1.0000,0.958333,1.0000,...,-0.020115,0.024756,0.024756,0.024756,-0.016705,0.024756,-0.045962,chr1,16645,16647
4,chr1:16664,0.984000,0.963000,1.000000,0.942000,1.000000,1.000000,1.0000,0.889000,0.9720,...,-0.083936,0.005449,0.035603,-0.018244,-0.013397,-0.018244,-0.036910,chr1,16664,16666

In [5]:
indf=indf.drop(['position'],axis=1)

In [6]:
indf.head()

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,...,DC-others,Eo-others,Tr-others,m4-others,Mg-others,Er-others,mB-others,chrom,start,end
0,0.879333,0.870667,0.954667,0.935667,0.918667,0.785000,0.8690,0.948000,0.9200,0.8825,...,0.046013,0.015859,-0.024526,0.056244,0.034167,-0.032064,0.037756,chr1,16138,16140
1,0.654000,0.641667,0.765667,0.697667,0.743333,0.569667,0.6395,0.660333,0.6400,0.7200,...,0.019654,-0.002244,0.083910,-0.038321,-0.037244,-0.101321,-0.158038,chr1,16242,16244
2,0.948667,1.000000,0.875000,0.884333,1.000000,0.741000,0.8750,0.889000,0.7335,1.0000,...,-0.017526,-0.184987,0.102013,0.102013,0.102013,0.102013,-0.191628,chr1,16633,16635
3,0.980333,0.972333,0.966667,0.946333,1.000000,0.958333,1.0000,0.958333,1.0000,1.0000,...,-0.020115,0.024756,0.024756,0.024756,-0.016705,0.024756,-0.045962,chr1,16645,16647
4,0.984000,0.963000,1.000000,0.942000,1.000000,1.000000,1.0000,0.889000,0.9720,1.0000,...,-0.083936,0.005449,0.035603,-0.018244,-0.013397,-0.018244,-0.036910,chr1,16664,16666

In [7]:
indf=indf.set_index(['chrom','start','end'])

In [8]:
indf.head()

                        CD4       CD8        nB        NK        Mn      mNeu  \
chrom start end
chr1  16138 16140  0.879333  0.870667  0.954667  0.935667  0.918667  0.785000
      16242 16244  0.654000  0.641667  0.765667  0.697667  0.743333  0.569667
      16633 16635  0.948667  1.000000  0.875000  0.884333  1.000000  0.741000
      16645 16647  0.980333  0.972333  0.966667  0.946333  1.000000  0.958333
      16664 16666  0.984000  0.963000  1.000000  0.942000  1.000000  1.000000

                       m8        DC      Eo      Tr  ...  Mn-others  \
chrom start end                                      ...
chr1  16138 16140  0.8690  0.948000  0.9200  0.8825  ...   0.014423
      16242 16244  0.6395  0.660333  0.6400  0.7200  ...   0.109038
      16633 16635  0.8750  0.889000  0.7335  1.0000  ...   0.102013
      16645 16647  1.0000  0.958333  1.0000  1.0000  ...   0.024756
      16664 16666  1.0000  0.889000  0.9720  1.0000  ...   0.035603

                   mNeu-others  m8-others  DC-others  Eo-others  Tr-others  \
chrom start end
chr1  16138 16140    -0.129526  -0.039064   0.046013   0.015859  -0.024526
      16242 16244    -0.077987  -0.002782   0.019654  -0.002244   0.083910
      16633 16635    -0.176910  -0.032603  -0.017526  -0.184987   0.102013
      16645 16647    -0.020115   0.024756  -0.020115   0.024756   0.024756
      16664 16666     0.035603   0.035603  -0.083936   0.005449   0.035603

                   m4-others  Mg-others  Er-others  mB-others
chrom start end
chr1  16138 16140   0.056244   0.034167  -0.032064   0.037756
      16242 16244  -0.038321  -0.037244  -0.101321  -0.158038
      16633 16635   0.102013   0.102013   0.102013  -0.191628
      16645 16647   0.024756  -0.016705   0.024756  -0.045962
      16664 16666  -0.018244  -0.013397  -0.018244  -0.036910

[5 rows x 28 columns]

In [9]:
indf=indf[scorecolumns]
indf.head()

                   CD4-others  CD8-others  nB-others  NK-others  Mn-others  \
chrom start end
chr1  16138 16140   -0.027936   -0.037269   0.053192   0.032731   0.014423
      16242 16244    0.012833   -0.000449   0.133090   0.059859   0.109038
      16633 16635    0.046731    0.102013  -0.032603  -0.022551   0.102013
      16645 16647    0.003577   -0.005038  -0.011141  -0.033038   0.024756
      16664 16666    0.018372   -0.004244   0.035603  -0.026859   0.035603

                   mNeu-others  m8-others  DC-others  Eo-others  Tr-others  \
chrom start end
chr1  16138 16140    -0.129526  -0.039064   0.046013   0.015859  -0.024526
      16242 16244    -0.077987  -0.002782   0.019654  -0.002244   0.083910
      16633 16635    -0.176910  -0.032603  -0.017526  -0.184987   0.102013
      16645 16647    -0.020115   0.024756  -0.020115   0.024756   0.024756
      16664 16666     0.035603   0.035603  -0.083936   0.005449   0.035603

                   m4-others  Mg-others  Er-others  mB-others
chrom start end
chr1  16138 16140   0.056244   0.034167  -0.032064   0.037756
      16242 16244  -0.038321  -0.037244  -0.101321  -0.158038
      16633 16635   0.102013   0.102013   0.102013  -0.191628
      16645 16647   0.024756  -0.016705   0.024756  -0.045962
      16664 16666  -0.018244  -0.013397  -0.018244  -0.036910

In [11]:
indf.to_csv(outfile+"_likebg.txt.gz",sep="\t", chunksize = 1000000, compression = 'gzip')

KeyboardInterrupt:

In [ ]:
indf=indf.reset_index()

In [ ]:
indf.head()

In [ ]:
indf=indf.drop(['end'],axis=1)

In [ ]:
indf.head()

In [ ]:
indf=indf.set_index(['chrom','start'])

In [ ]:
indf.to_csv(outfile+"_noend.txt.gz",sep="\t", chunksize = 100000, compression = 'gzip')