In [1]:
import pandas as pd
from collections import defaultdict

infile='/Users/irffanalahi/Research/Research_update/SoftRD/hashtable_stats/B22withLTME/convertprevTILtodeltabased/oldSMdeltabased_dummytomatcholdSM.txt'


cellType='TIL'

indf=pd.read_csv(infile,sep="\t",index_col=['chrom','start'])
indf.head()

               PBL-others  TIL-others  MEL_TUMOR-others
chrom start
chr1  2259074   -0.172056   -0.426139          0.598194
      2259134   -0.056833   -0.437833          0.494667
      2259183    0.018500   -0.541250          0.522750
      2259191    0.007667   -0.540833          0.533167
      2259197   -0.023000   -0.521250          0.544250

In [2]:
indf['mincolname']=indf.idxmin(axis=1)
indf.head()

               PBL-others  TIL-others  MEL_TUMOR-others  mincolname
chrom start
chr1  2259074   -0.172056   -0.426139          0.598194  TIL-others
      2259134   -0.056833   -0.437833          0.494667  TIL-others
      2259183    0.018500   -0.541250          0.522750  TIL-others
      2259191    0.007667   -0.540833          0.533167  TIL-others
      2259197   -0.023000   -0.521250          0.544250  TIL-others

In [3]:
indf.to_csv(infile+"_mincolname.txt",sep="\t")