In [1]:
import pandas as pd
from collections import defaultdict
import sys
import time
start_time = time.time()

infile="/Users/irffanalahi/Research/Research_update/SoftRD/hashtable_stats/B22withLTME/v2_2steps/generateSM/BL22LTMEtraining_all_matrixCin_nr0.4_imputed_romean_bg_othermean_intwith_TILmelTraining_TIL_-0.4_onlypos"

outfile=infile







##########when WG just chrom start, else chrom start end
indf=pd.read_csv(infile,sep="\t") #############

indf.set_index(['chrom','start','end'],inplace=True)


indf.head()

                     NaiveCD4-others  NaiveCD8-others  nB-others  NK-others  \
chrom start  end
chr1  940035 940037        -0.048575        -0.140401  -0.100054   0.122555
      966108 966110         0.179261         0.220652  -0.105609  -0.072565
      966124 966126         0.169681         0.151594  -0.051188  -0.018493
      970723 970725         0.043659        -0.053384  -0.053036  -0.079123
      980586 980588         0.108268         0.153833   0.060268   0.265138

                     PC-others  Mono-others  M0-others  M1-others  M2-others  \
chrom start  end
chr1  940035 940037   0.127772    -0.121271   0.012642  -0.184923  -0.038836
      966108 966110   0.148652    -0.134478  -0.260391  -0.262478  -0.292043
      966124 966126  -0.020580    -0.218145  -0.169101  -0.137449  -0.254319
      970723 970725   0.170268    -0.060688  -0.082601  -0.031819  -0.101732
      980586 980588  -0.366167     0.176094   0.096442   0.168790   0.207746

                     iDC-others  ...  Eo-others  Tregs-others  em4-others  \
chrom start  end                 ...
chr1  940035 940037    0.015077  ...  -0.160749      0.075599    0.067251
      966108 966110   -0.245609  ...  -0.155348     -0.082826   -0.045261
      966124 966126   -0.217275  ...  -0.230841     -0.162493   -0.082667
      970723 970725   -0.131993  ...  -0.052688      0.071486    0.057399
      980586 980588    0.163920  ...   0.144616     -0.114688   -0.186688

                     ed8-others  Mg-others  cm4-others  Er-others  mB-others  \
chrom start  end
chr1  940035 940037    0.227946  -0.007880    0.058381   0.010381   0.026555
      966108 966110    0.323609   0.131609    0.100826   0.001696   0.058043
      966124 966126    0.239768   0.354551   -0.050319   0.394203  -0.093623
      970723 970725    0.041225  -0.090775    0.070964  -0.105906   0.054268
      980586 980588   -0.270167   0.169138   -0.145993   0.120094  -0.327036

                     TIL-others  MelTumor-others
chrom start  end
chr1  940035 940037   -0.122245         0.328120
      966108 966110    0.169348         0.597000
      966124 966126    0.106725         0.748464
      970723 970725   -0.110080         0.363659
      980586 980588   -0.245471         0.205138

[5 rows x 24 columns]

In [2]:
negindf=-1*indf
negindf.head()

                     NaiveCD4-others  NaiveCD8-others  nB-others  NK-others  \
chrom start  end
chr1  940035 940037         0.048575         0.140401   0.100054  -0.122555
      966108 966110        -0.179261        -0.220652   0.105609   0.072565
      966124 966126        -0.169681        -0.151594   0.051188   0.018493
      970723 970725        -0.043659         0.053384   0.053036   0.079123
      980586 980588        -0.108268        -0.153833  -0.060268  -0.265138

                     PC-others  Mono-others  M0-others  M1-others  M2-others  \
chrom start  end
chr1  940035 940037  -0.127772     0.121271  -0.012642   0.184923   0.038836
      966108 966110  -0.148652     0.134478   0.260391   0.262478   0.292043
      966124 966126   0.020580     0.218145   0.169101   0.137449   0.254319
      970723 970725  -0.170268     0.060688   0.082601   0.031819   0.101732
      980586 980588   0.366167    -0.176094  -0.096442  -0.168790  -0.207746

                     iDC-others  ...  Eo-others  Tregs-others  em4-others  \
chrom start  end                 ...
chr1  940035 940037   -0.015077  ...   0.160749     -0.075599   -0.067251
      966108 966110    0.245609  ...   0.155348      0.082826    0.045261
      966124 966126    0.217275  ...   0.230841      0.162493    0.082667
      970723 970725    0.131993  ...   0.052688     -0.071486   -0.057399
      980586 980588   -0.163920  ...  -0.144616      0.114688    0.186688

                     ed8-others  Mg-others  cm4-others  Er-others  mB-others  \
chrom start  end
chr1  940035 940037   -0.227946   0.007880   -0.058381  -0.010381  -0.026555
      966108 966110   -0.323609  -0.131609   -0.100826  -0.001696  -0.058043
      966124 966126   -0.239768  -0.354551    0.050319  -0.394203   0.093623
      970723 970725   -0.041225   0.090775   -0.070964   0.105906  -0.054268
      980586 980588    0.270167  -0.169138    0.145993  -0.120094   0.327036

                     TIL-others  MelTumor-others
chrom start  end
chr1  940035 940037    0.122245        -0.328120
      966108 966110   -0.169348        -0.597000
      966124 966126   -0.106725        -0.748464
      970723 970725    0.110080        -0.363659
      980586 980588    0.245471        -0.205138

[5 rows x 24 columns]

In [3]:
alldelta=[.05,.1,.5,.6,.7,.8,0.9]

In [4]:
scorecolumns=negindf.columns

In [5]:
celltypeStats=defaultdict(list)

allindex=defaultdict(list)
for score in scorecolumns:

    for delta in alldelta:
        tmpdf=negindf[negindf[score]>=delta]
        allindex[delta]=allindex[delta]+tmpdf.index.tolist()
        
        celltypeStats[score]=celltypeStats[score]+[tmpdf.shape[0]]

In [6]:
celltypeStatsdf=pd.DataFrame.from_dict(celltypeStats, orient='index',columns=alldelta)
celltypeStatsdf.index.name = 'Celltype'
celltypeStatsdf.head()

                  0.05   0.10   0.50  0.60  0.70  0.80  0.90
Celltype
NaiveCD4-others  34049  16028   2130   575    38     0     0
NaiveCD8-others  36163  17985   1652   208     6     0     0
nB-others        36117  14391    547   211    60     4     0
NK-others        50371  26835   2779  1220   393    17     0
PC-others        48076  38618  10731  4483   752    29     0

In [7]:
celltypeStatsdf.to_csv(outfile+"_stats.txt",sep="\t")

In [8]:
alluniqueindex=defaultdict(list)
for key in allindex:
    alluniqueindex[key]=list(set(allindex[key]))

In [9]:
selected=0.5

In [10]:
indf.head()

                     NaiveCD4-others  NaiveCD8-others  nB-others  NK-others  \
chrom start  end
chr1  940035 940037        -0.048575        -0.140401  -0.100054   0.122555
      966108 966110         0.179261         0.220652  -0.105609  -0.072565
      966124 966126         0.169681         0.151594  -0.051188  -0.018493
      970723 970725         0.043659        -0.053384  -0.053036  -0.079123
      980586 980588         0.108268         0.153833   0.060268   0.265138

                     PC-others  Mono-others  M0-others  M1-others  M2-others  \
chrom start  end
chr1  940035 940037   0.127772    -0.121271   0.012642  -0.184923  -0.038836
      966108 966110   0.148652    -0.134478  -0.260391  -0.262478  -0.292043
      966124 966126  -0.020580    -0.218145  -0.169101  -0.137449  -0.254319
      970723 970725   0.170268    -0.060688  -0.082601  -0.031819  -0.101732
      980586 980588  -0.366167     0.176094   0.096442   0.168790   0.207746

                     iDC-others  ...  Eo-others  Tregs-others  em4-others  \
chrom start  end                 ...
chr1  940035 940037    0.015077  ...  -0.160749      0.075599    0.067251
      966108 966110   -0.245609  ...  -0.155348     -0.082826   -0.045261
      966124 966126   -0.217275  ...  -0.230841     -0.162493   -0.082667
      970723 970725   -0.131993  ...  -0.052688      0.071486    0.057399
      980586 980588    0.163920  ...   0.144616     -0.114688   -0.186688

                     ed8-others  Mg-others  cm4-others  Er-others  mB-others  \
chrom start  end
chr1  940035 940037    0.227946  -0.007880    0.058381   0.010381   0.026555
      966108 966110    0.323609   0.131609    0.100826   0.001696   0.058043
      966124 966126    0.239768   0.354551   -0.050319   0.394203  -0.093623
      970723 970725    0.041225  -0.090775    0.070964  -0.105906   0.054268
      980586 980588   -0.270167   0.169138   -0.145993   0.120094  -0.327036

                     TIL-others  MelTumor-others
chrom start  end
chr1  940035 940037   -0.122245         0.328120
      966108 966110    0.169348         0.597000
      966124 966126    0.106725         0.748464
      970723 970725   -0.110080         0.363659
      980586 980588   -0.245471         0.205138

[5 rows x 24 columns]

In [11]:
sm=indf.loc[alluniqueindex[selected]]

In [12]:
smonlyindex=sm.reset_index()
smonlyindex.head()

,chrom,start,end,NaiveCD4-others,NaiveCD8-others,nB-others,NK-others,PC-others,Mono-others,M0-others,...,Eo-others,Tregs-others,em4-others,ed8-others,Mg-others,cm4-others,Er-others,mB-others,TIL-others,MelTumor-others
0,chr22,36005364,36005366,0.219645,0.183471,0.236341,0.187297,-0.673225,0.141036,0.214428,...,0.078428,-0.199659,-0.374442,-0.283138,0.067471,-0.086964,0.002775,0.004862,-0.321399,0.183297
1,chr22,24409844,24409846,0.147384,0.020080,0.121297,-0.072790,-0.176442,0.101471,0.141123,...,0.089645,0.123558,-0.083051,-0.741486,0.167906,0.156428,0.105297,0.061471,-0.314355,0.155384
2,chr14,47654290,47654292,0.174181,0.164094,0.258007,0.156094,-0.543384,0.159572,0.175920,...,0.081138,-0.182862,-0.339384,-0.423906,0.200094,-0.184428,0.055572,-0.189645,-0.294862,0.357659
3,chr10,14067293,14067295,0.077167,0.114558,0.138036,0.093167,-0.712746,0.087254,0.178036,...,-0.002833,-0.086833,-0.031529,-0.057094,-0.088920,-0.061268,-0.019529,0.090558,-0.207529,0.241341
4,chr5,176482304,176482306,0.135159,0.086464,0.184899,-0.712493,0.048203,0.187681,0.190812,...,0.064899,-0.065014,-0.102058,-0.499623,0.237072,-0.211623,0.120725,-0.323275,-0.249884,0.176029

In [13]:
smonlyindex=(smonlyindex[['chrom','start','end']]).copy()
smonlyindex.head()

   chrom      start        end
0  chr22   36005364   36005366
1  chr22   24409844   24409846
2  chr14   47654290   47654292
3  chr10   14067293   14067295
4   chr5  176482304  176482306

In [14]:
smonlyindex['startoffset']=smonlyindex['start']-10
smonlyindex['endoffset']=smonlyindex['end']+10

smonlyindex.head()

   chrom      start        end  startoffset  endoffset
0  chr22   36005364   36005366     36005354   36005376
1  chr22   24409844   24409846     24409834   24409856
2  chr14   47654290   47654292     47654280   47654302
3  chr10   14067293   14067295     14067283   14067305
4   chr5  176482304  176482306    176482294  176482316

In [15]:
smonlyindex=smonlyindex.drop(['start','end'],axis=1)

smonlyindex.head()

   chrom  startoffset  endoffset
0  chr22     36005354   36005376
1  chr22     24409834   24409856
2  chr14     47654280   47654302
3  chr10     14067283   14067305
4   chr5    176482294  176482316

In [16]:
if smonlyindex[smonlyindex.duplicated()].shape[0]!=0:
    sys.exit(1)

In [17]:
smonlyindex.to_csv(outfile+"_sm_forbam"+str(selected)+".txt",sep="\t",header=False,index=False)

In [18]:
sm=sm.reset_index()

In [19]:
sm=sm.drop(['end'],axis=1)
sm.head()

,chrom,start,NaiveCD4-others,NaiveCD8-others,nB-others,NK-others,PC-others,Mono-others,M0-others,M1-others,...,Eo-others,Tregs-others,em4-others,ed8-others,Mg-others,cm4-others,Er-others,mB-others,TIL-others,MelTumor-others
0,chr22,36005364,0.219645,0.183471,0.236341,0.187297,-0.673225,0.141036,0.214428,0.219645,...,0.078428,-0.199659,-0.374442,-0.283138,0.067471,-0.086964,0.002775,0.004862,-0.321399,0.183297
1,chr22,24409844,0.147384,0.020080,0.121297,-0.072790,-0.176442,0.101471,0.141123,0.096601,...,0.089645,0.123558,-0.083051,-0.741486,0.167906,0.156428,0.105297,0.061471,-0.314355,0.155384
2,chr14,47654290,0.174181,0.164094,0.258007,0.156094,-0.543384,0.159572,0.175920,0.167225,...,0.081138,-0.182862,-0.339384,-0.423906,0.200094,-0.184428,0.055572,-0.189645,-0.294862,0.357659
3,chr10,14067293,0.077167,0.114558,0.138036,0.093167,-0.712746,0.087254,0.178036,0.124123,...,-0.002833,-0.086833,-0.031529,-0.057094,-0.088920,-0.061268,-0.019529,0.090558,-0.207529,0.241341
4,chr5,176482304,0.135159,0.086464,0.184899,-0.712493,0.048203,0.187681,0.190812,0.190116,...,0.064899,-0.065014,-0.102058,-0.499623,0.237072,-0.211623,0.120725,-0.323275,-0.249884,0.176029

In [20]:
if sm[sm.duplicated()].shape[0]!=0:
    sys.exit(1)

In [21]:
sm.to_csv(outfile+"_sm_"+str(selected)+".txt",sep="\t",index=False)

In [22]:
end_time = time.time()

time_elapsed = (end_time - start_time)

print(time_elapsed)

5.0562779903411865