In [1]:
import pandas as pd
from collections import defaultdict
import sys
import time
start_time = time.time()

infile="/Users/irffanalahi/Research/Research_update/SoftRD/hashtable_stats/BL22/BL22_all_matrixCin_nr0.4_imputed_rowmean_bg_othermean_interwithgeneprom1000_1000.txt"


outfile=infile







##########when WG just chrom start, else chrom start end
indf=pd.read_csv(infile,sep="\t") #############

indf.set_index(['chrom','start','end'],inplace=True)


indf.head()

                     NaiveCD4-others  NaiveCD8-others  nB-others  NK-others  \
chrom start  end
chr1  922981 922983         0.016325         0.003056   0.000262   0.012833
      922991 922993         0.021794         0.010270  -0.013825  -0.002651
      923025 923027         0.149595         0.124452   0.084643   0.091627
      923048 923050        -0.003675         0.001563   0.017278  -0.002627
      923053 923055         0.076921         0.007778  -0.027143   0.075175

                     PC-others  Mono-others  M0-others  M1-others  M2-others  \
chrom start  end
chr1  922981 922983  -0.177484     0.047056   0.024706   0.022960   0.027849
      922991 922993   0.004333     0.013762   0.021794   0.013762   0.006778
      923025 923027  -0.483167    -0.053294   0.038548  -0.030944  -0.011738
      923048 923050  -0.222976    -0.014500   0.003310   0.019024   0.019373
      923053 923055  -0.360984     0.021397  -0.040762   0.008476  -0.007937

                     iDC-others  ...  cm8-others  em8-others  Eo-others  \
chrom start  end                 ...
chr1  922981 922983    0.029071  ...    0.004452    0.003929   0.022786
      922991 922993   -0.036349  ...   -0.004921   -0.035302   0.012365
      923025 923027   -0.007024  ...    0.035929    0.034357  -0.011738
      923048 923050   -0.048548  ...    0.052024    0.028976  -0.024976
      923053 923055   -0.039540  ...    0.035365    0.051603  -0.152683

                     Tregs-others  em4-others  ed8-others  Mg-others  \
chrom start  end
chr1  922981 922983     -0.008643   -0.033262    0.001833   0.011786
      922991 922993     -0.036873   -0.015921   -0.009635   0.028079
      923025 923027      0.018643   -0.040024    0.025452   0.089881
      923048 923050      0.030024    0.036310    0.046786   0.030548
      923053 923055      0.060508    0.044270    0.114460   0.028032

                     cm4-others  Er-others  mB-others
chrom start  end
chr1  922981 922983    0.003929  -0.002357  -0.011262
      922991 922993   -0.012254   0.001365   0.006079
      923025 923027   -0.005976   0.045881  -0.051548
      923048 923050    0.036310  -0.001405   0.034738
      923053 923055    0.049508   0.029079   0.009698

[5 rows x 22 columns]

In [2]:
negindf=-1*indf
negindf.head()

                     NaiveCD4-others  NaiveCD8-others  nB-others  NK-others  \
chrom start  end
chr1  922981 922983        -0.016325        -0.003056  -0.000262  -0.012833
      922991 922993        -0.021794        -0.010270   0.013825   0.002651
      923025 923027        -0.149595        -0.124452  -0.084643  -0.091627
      923048 923050         0.003675        -0.001563  -0.017278   0.002627
      923053 923055        -0.076921        -0.007778   0.027143  -0.075175

                     PC-others  Mono-others  M0-others  M1-others  M2-others  \
chrom start  end
chr1  922981 922983   0.177484    -0.047056  -0.024706  -0.022960  -0.027849
      922991 922993  -0.004333    -0.013762  -0.021794  -0.013762  -0.006778
      923025 923027   0.483167     0.053294  -0.038548   0.030944   0.011738
      923048 923050   0.222976     0.014500  -0.003310  -0.019024  -0.019373
      923053 923055   0.360984    -0.021397   0.040762  -0.008476   0.007937

                     iDC-others  ...  cm8-others  em8-others  Eo-others  \
chrom start  end                 ...
chr1  922981 922983   -0.029071  ...   -0.004452   -0.003929  -0.022786
      922991 922993    0.036349  ...    0.004921    0.035302  -0.012365
      923025 923027    0.007024  ...   -0.035929   -0.034357   0.011738
      923048 923050    0.048548  ...   -0.052024   -0.028976   0.024976
      923053 923055    0.039540  ...   -0.035365   -0.051603   0.152683

                     Tregs-others  em4-others  ed8-others  Mg-others  \
chrom start  end
chr1  922981 922983      0.008643    0.033262   -0.001833  -0.011786
      922991 922993      0.036873    0.015921    0.009635  -0.028079
      923025 923027     -0.018643    0.040024   -0.025452  -0.089881
      923048 923050     -0.030024   -0.036310   -0.046786  -0.030548
      923053 923055     -0.060508   -0.044270   -0.114460  -0.028032

                     cm4-others  Er-others  mB-others
chrom start  end
chr1  922981 922983   -0.003929   0.002357   0.011262
      922991 922993    0.012254  -0.001365  -0.006079
      923025 923027    0.005976  -0.045881   0.051548
      923048 923050   -0.036310   0.001405  -0.034738
      923053 923055   -0.049508  -0.029079  -0.009698

[5 rows x 22 columns]

In [3]:
alldelta=[.05,.1,.5,.6,.7,.8,0.9]

In [4]:
scorecolumns=negindf.columns

In [5]:
celltypeStats=defaultdict(list)

allindex=defaultdict(list)
for score in scorecolumns:

    for delta in alldelta:
        tmpdf=negindf[negindf[score]>=delta]
        allindex[delta]=allindex[delta]+tmpdf.index.tolist()
        
        celltypeStats[score]=celltypeStats[score]+[tmpdf.shape[0]]

In [6]:
celltypeStatsdf=pd.DataFrame.from_dict(celltypeStats, orient='index',columns=alldelta)
celltypeStatsdf.index.name = 'Celltype'
celltypeStatsdf.head()

                    0.05     0.10     0.50    0.60    0.70    0.80  0.90
Celltype
NaiveCD4-others   200813    89044     8882    3454     805      74     0
NaiveCD8-others   265052   106630     8635    2507     358       5     0
nB-others         322137   161804    23885   16043    9888    4436   278
NK-others         604130   313179    29825   17545    8853    2701    91
PC-others        5127042  4561767  1556598  895489  409039  116295  5119

In [7]:
celltypeStatsdf.to_csv(outfile+"_stats.txt",sep="\t")

In [8]:
alluniqueindex=defaultdict(list)
for key in allindex:
    alluniqueindex[key]=list(set(allindex[key]))

In [9]:
selected=0.7

In [10]:
indf.head()

                     NaiveCD4-others  NaiveCD8-others  nB-others  NK-others  \
chrom start  end
chr1  922981 922983         0.016325         0.003056   0.000262   0.012833
      922991 922993         0.021794         0.010270  -0.013825  -0.002651
      923025 923027         0.149595         0.124452   0.084643   0.091627
      923048 923050        -0.003675         0.001563   0.017278  -0.002627
      923053 923055         0.076921         0.007778  -0.027143   0.075175

                     PC-others  Mono-others  M0-others  M1-others  M2-others  \
chrom start  end
chr1  922981 922983  -0.177484     0.047056   0.024706   0.022960   0.027849
      922991 922993   0.004333     0.013762   0.021794   0.013762   0.006778
      923025 923027  -0.483167    -0.053294   0.038548  -0.030944  -0.011738
      923048 923050  -0.222976    -0.014500   0.003310   0.019024   0.019373
      923053 923055  -0.360984     0.021397  -0.040762   0.008476  -0.007937

                     iDC-others  ...  cm8-others  em8-others  Eo-others  \
chrom start  end                 ...
chr1  922981 922983    0.029071  ...    0.004452    0.003929   0.022786
      922991 922993   -0.036349  ...   -0.004921   -0.035302   0.012365
      923025 923027   -0.007024  ...    0.035929    0.034357  -0.011738
      923048 923050   -0.048548  ...    0.052024    0.028976  -0.024976
      923053 923055   -0.039540  ...    0.035365    0.051603  -0.152683

                     Tregs-others  em4-others  ed8-others  Mg-others  \
chrom start  end
chr1  922981 922983     -0.008643   -0.033262    0.001833   0.011786
      922991 922993     -0.036873   -0.015921   -0.009635   0.028079
      923025 923027      0.018643   -0.040024    0.025452   0.089881
      923048 923050      0.030024    0.036310    0.046786   0.030548
      923053 923055      0.060508    0.044270    0.114460   0.028032

                     cm4-others  Er-others  mB-others
chrom start  end
chr1  922981 922983    0.003929  -0.002357  -0.011262
      922991 922993   -0.012254   0.001365   0.006079
      923025 923027   -0.005976   0.045881  -0.051548
      923048 923050    0.036310  -0.001405   0.034738
      923053 923055    0.049508   0.029079   0.009698

[5 rows x 22 columns]

In [11]:
sm=indf.loc[alluniqueindex[selected]]

In [12]:
smonlyindex=sm.reset_index()
smonlyindex.head()

,chrom,start,end,NaiveCD4-others,NaiveCD8-others,nB-others,NK-others,PC-others,Mono-others,M0-others,...,cm8-others,em8-others,Eo-others,Tregs-others,em4-others,ed8-others,Mg-others,cm4-others,Er-others,mB-others
0,chr6,37356861,37356863,0.146444,0.008159,0.145048,-0.834825,-0.045270,0.190095,0.143651,...,0.014619,-0.464143,0.148190,0.150286,-0.036714,-0.792048,0.146619,0.123048,0.065952,0.089524
1,chr3,53572908,53572910,0.091024,0.062040,0.103595,0.032706,-0.870690,0.104294,0.111976,...,0.045452,-0.010595,0.074262,0.020310,0.016643,-0.075024,-0.013214,0.066405,-0.152024,0.092595
2,chr2,11600694,11600696,0.115452,0.113008,0.091008,0.116151,-0.708675,0.106024,0.049103,...,-0.100706,-0.026849,0.042817,0.003008,0.015579,-0.001183,-0.070325,-0.022135,-0.218563,0.049103
3,chr11,2310163,2310165,0.086937,0.090778,0.082746,0.024429,-0.848238,0.091825,0.042587,...,0.063714,-0.067238,0.060571,0.079429,-0.092905,-0.110714,0.121333,-0.010667,0.069476,-0.108095
4,chr2,141239094,141239096,0.178730,0.144857,0.211206,0.117270,-0.725016,0.060000,0.141714,...,-0.039000,-0.130143,-0.000238,-0.084048,-0.134857,-0.172048,-0.071476,-0.029571,0.005000,0.063667

In [13]:
smonlyindex=(smonlyindex[['chrom','start','end']]).copy()
smonlyindex.head()

   chrom      start        end
0   chr6   37356861   37356863
1   chr3   53572908   53572910
2   chr2   11600694   11600696
3  chr11    2310163    2310165
4   chr2  141239094  141239096

In [14]:
smonlyindex['startoffset']=smonlyindex['start']-10
smonlyindex['endoffset']=smonlyindex['end']+10

smonlyindex.head()

   chrom      start        end  startoffset  endoffset
0   chr6   37356861   37356863     37356851   37356873
1   chr3   53572908   53572910     53572898   53572920
2   chr2   11600694   11600696     11600684   11600706
3  chr11    2310163    2310165      2310153    2310175
4   chr2  141239094  141239096    141239084  141239106

In [15]:
smonlyindex=smonlyindex.drop(['start','end'],axis=1)

smonlyindex.head()

   chrom  startoffset  endoffset
0   chr6     37356851   37356873
1   chr3     53572898   53572920
2   chr2     11600684   11600706
3  chr11      2310153    2310175
4   chr2    141239084  141239106

In [16]:
if smonlyindex[smonlyindex.duplicated()].shape[0]!=0:
    sys.exit(1)

In [17]:
smonlyindex.to_csv(outfile+"_sm_forbam"+str(selected)+".txt",sep="\t",header=False,index=False)

In [18]:
sm=sm.reset_index()

In [19]:
sm=sm.drop(['end'],axis=1)
sm.head()

,chrom,start,NaiveCD4-others,NaiveCD8-others,nB-others,NK-others,PC-others,Mono-others,M0-others,M1-others,...,cm8-others,em8-others,Eo-others,Tregs-others,em4-others,ed8-others,Mg-others,cm4-others,Er-others,mB-others
0,chr6,37356861,0.146444,0.008159,0.145048,-0.834825,-0.045270,0.190095,0.143651,0.159365,...,0.014619,-0.464143,0.148190,0.150286,-0.036714,-0.792048,0.146619,0.123048,0.065952,0.089524
1,chr3,53572908,0.091024,0.062040,0.103595,0.032706,-0.870690,0.104294,0.111976,0.050865,...,0.045452,-0.010595,0.074262,0.020310,0.016643,-0.075024,-0.013214,0.066405,-0.152024,0.092595
2,chr2,11600694,0.115452,0.113008,0.091008,0.116151,-0.708675,0.106024,0.049103,0.165389,...,-0.100706,-0.026849,0.042817,0.003008,0.015579,-0.001183,-0.070325,-0.022135,-0.218563,0.049103
3,chr11,2310163,0.086937,0.090778,0.082746,0.024429,-0.848238,0.091825,0.042587,0.092175,...,0.063714,-0.067238,0.060571,0.079429,-0.092905,-0.110714,0.121333,-0.010667,0.069476,-0.108095
4,chr2,141239094,0.178730,0.144857,0.211206,0.117270,-0.725016,0.060000,0.141714,0.088635,...,-0.039000,-0.130143,-0.000238,-0.084048,-0.134857,-0.172048,-0.071476,-0.029571,0.005000,0.063667

In [20]:
if sm[sm.duplicated()].shape[0]!=0:
    sys.exit(1)

In [21]:
sm.to_csv(outfile+"_sm_"+str(selected)+".txt",sep="\t",index=False)

In [22]:
end_time = time.time()

time_elapsed = (end_time - start_time)

print(time_elapsed)

298.6394498348236