In [1]:
import pandas as pd
from collections import defaultdict

infile='/Users/irffanalahi/Research/Research_update/SoftRD/hashtable_stats/tieredApproach/BL22_groupv2/All/BL22tieredSM/allct_towardsSM_dummy_mean_SM.txt_unique'

indf=pd.read_csv(infile,sep="\t",index_col=['chrom','start'])
indf.head()

                NaiveCD4-others  NaiveCD8-others  nB-others  NK-others  \
chrom start
chr1  6012593               0.9              0.9        0.9        0.9
      10525350              0.9              0.9        0.9        0.9
      10525356              0.9              0.9        0.9        0.9
      10525449              0.9              0.9        0.9        0.9
      13765075              0.9              0.9        0.9        0.9

                PC-others  Mono-others  M0-others  M1-others  M2-others  \
chrom start
chr1  6012593         0.9          0.9        0.9        0.9        0.9
      10525350        0.9          0.9        0.9        0.9        0.9
      10525356        0.9          0.9        0.9        0.9        0.9
      10525449        0.9          0.9        0.9        0.9        0.9
      13765075        0.9          0.9        0.9        0.9        0.9

                iDC-others  ...  cm8-others  em8-others  Eo-others  \
chrom start                 ...
chr1  6012593          0.9  ...         0.9         0.9        0.9
      10525350         0.9  ...         0.9         0.9        0.9
      10525356         0.9  ...         0.9         0.9        0.9
      10525449         0.9  ...         0.9         0.9        0.9
      13765075         0.9  ...         0.9         0.9        0.9

                Tregs-others  em4-others  ed8-others  Mg-others  cm4-others  \
chrom start
chr1  6012593            0.9         0.9   -0.800627        0.9         0.9
      10525350           0.9         0.9   -0.871885        0.9         0.9
      10525356           0.9         0.9   -0.870743        0.9         0.9
      10525449           0.9         0.9   -0.873007        0.9         0.9
      13765075           0.9         0.9   -0.820474        0.9         0.9

                Er-others  mB-others
chrom start
chr1  6012593         0.9        0.9
      10525350        0.9        0.9
      10525356        0.9        0.9
      10525449        0.9        0.9
      13765075        0.9        0.9

[5 rows x 22 columns]

In [2]:
indf['mincolname']=indf.idxmin(axis=1)
indf.head()

                NaiveCD4-others  NaiveCD8-others  nB-others  NK-others  \
chrom start
chr1  6012593               0.9              0.9        0.9        0.9
      10525350              0.9              0.9        0.9        0.9
      10525356              0.9              0.9        0.9        0.9
      10525449              0.9              0.9        0.9        0.9
      13765075              0.9              0.9        0.9        0.9

                PC-others  Mono-others  M0-others  M1-others  M2-others  \
chrom start
chr1  6012593         0.9          0.9        0.9        0.9        0.9
      10525350        0.9          0.9        0.9        0.9        0.9
      10525356        0.9          0.9        0.9        0.9        0.9
      10525449        0.9          0.9        0.9        0.9        0.9
      13765075        0.9          0.9        0.9        0.9        0.9

                iDC-others  ...  em8-others  Eo-others  Tregs-others  \
chrom start                 ...
chr1  6012593          0.9  ...         0.9        0.9           0.9
      10525350         0.9  ...         0.9        0.9           0.9
      10525356         0.9  ...         0.9        0.9           0.9
      10525449         0.9  ...         0.9        0.9           0.9
      13765075         0.9  ...         0.9        0.9           0.9

                em4-others  ed8-others  Mg-others  cm4-others  Er-others  \
chrom start
chr1  6012593          0.9   -0.800627        0.9         0.9        0.9
      10525350         0.9   -0.871885        0.9         0.9        0.9
      10525356         0.9   -0.870743        0.9         0.9        0.9
      10525449         0.9   -0.873007        0.9         0.9        0.9
      13765075         0.9   -0.820474        0.9         0.9        0.9

                mB-others  mincolname
chrom start
chr1  6012593         0.9  ed8-others
      10525350        0.9  ed8-others
      10525356        0.9  ed8-others
      10525449        0.9  ed8-others
      13765075        0.9  ed8-others

[5 rows x 23 columns]

In [3]:
grouped=indf.groupby('mincolname')
outlist=defaultdict(list)
for name, group in grouped:
    tempct=name.replace('-others','')
    outlist[tempct].append(group.shape[0])

In [4]:
outdf=pd.DataFrame.from_dict(outlist,orient='index',columns=['#CpG'])
outdf.index.name='Celltype'
outdf.head()

          #CpG
Celltype
Eo        4077
Er         737
M0         296
M1         925
M2        1074

In [5]:
outdf.to_csv(infile+"_info.txt",sep="\t")

In [6]:
indf.to_csv(infile+"_withmincol.txt",sep="\t")