In [1]:
import pandas as pd

In [2]:
f="/Users/irffanalahi/Research/Research_code/gitignorefolder/MHB_per_read/moretest/diagnosisthesm/blwithneu_hypo_stat.txt_0.01_2_g100.txtWithSurrounding.txt_1cpgnc_withoutheader_sorted_headeradded.txt_cyberin_allcombined.txt"
df=pd.read_csv(f,sep="\t",index_col=0)
df.head()

,celltype,blockchr,blockstart,blockend,CD14,CD19,CD4,CD8,CD56,Neu,...,eC0067N51_cytnk.bw.bedgraph_rolled,eS01E8O51_cytnk.bw.bedgraph_rolled,fC00184A3bs_matneu.bw.bedgraph_rolled,fC001UYA1bs_matneu.bw.bedgraph_rolled,fC004GD51_matneu.bw.bedgraph_rolled,pvalue,qvalue,fold_change,class1,class2
position,,,,,,,,,,,,,,,,,,,,,
chr1:8419832,['CD4'],chr1,8419682,8419982,6.1,6.5,71.75,1.0,4.4,3.6,...,1.0,8.5,1.0,6.9,3.6,4.680230e-06,0.000116,4.493672,"[False, False, False, False, False, False, Tru...","[True, True, True, True, True, True, False, Fa..."
chr1:8419857,['CD4'],chr1,8419682,8419982,3.9,1.0,80.45,9.7,3.5,6.6,...,6.6,3.5,3.6,8.5,6.6,8.510932e-08,0.000006,4.478762,"[False, False, False, False, False, False, Tru...","[True, True, True, True, True, True, False, Fa..."
chr1:8419860,['CD4'],chr1,8419682,8419982,1.0,6.3,64.80,4.1,1.0,6.1,...,6.7,1.0,5.5,6.1,6.3,7.874244e-08,0.000005,4.470470,"[False, False, False, False, False, False, Tru...","[True, True, True, True, True, True, False, Fa..."
chr1:9236050,['Neu'],chr1,9235902,9236208,7.2,4.0,5.55,1.0,1.0,74.7,...,1.0,8.1,69.8,74.7,89.2,8.714560e-09,0.000022,4.863852,"[False, False, False, False, False, False, Fal...","[True, True, True, True, True, True, True, Tru..."
chr1:9236052,['Neu'],chr1,9235902,9236208,4.2,1.0,1.00,1.0,1.0,85.2,...,1.0,1.0,87.7,85.2,65.7,1.497616e-10,0.000003,5.544913,"[False, False, False, False, False, False, Fal...","[True, True, True, True, True, True, True, Tru..."

In [3]:
df.shape

(1956, 32)

In [4]:
df=df.dropna(axis=0)
df.shape

(1931, 32)

In [5]:
df.to_csv(f+"_noNa.txt",sep="\t")
print("done")

done