In [1]:
import pandas as pd
UCSC_genetrack='/Users/irffanalahi/Research/Research_update/GENE/TCR_VDJ/All_Genecode_V40_gene.txt'

UCSC_genedf=pd.read_csv(UCSC_genetrack,sep='\t')

UCSC_genedf.head()

,#bin,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,score,name2,cdsStartStat,cdsEndStat,exonFrames
0,0,ENST00000684719.1,chr1,-,67092164,67134970,67093004,67127240,8,"67092164,67095234,67096251,67115351,67125751,6...","67093604,67095421,67096321,67115464,67125909,6...",0,C1orf141,cmpl,cmpl,"0,2,1,2,0,0,-1,-1,"
1,0,ENST00000371007.6,chr1,-,67092164,67231852,67093004,67127240,8,"67092164,67095234,67096251,67115351,67125751,6...","67093604,67095421,67096321,67115464,67125909,6...",0,C1orf141,cmpl,cmpl,"0,2,1,2,0,0,-1,-1,"
2,0,ENST00000371006.5,chr1,-,67092175,67127261,67093004,67127240,6,"67092175,67095234,67096251,67115351,67125751,6...","67093604,67095421,67096321,67115464,67125909,6...",0,C1orf141,cmpl,cmpl,"0,2,1,2,0,0,"
3,0,ENST00000475209.6,chr1,-,67092175,67127261,67093579,67127240,7,"67092175,67096251,67103237,67111576,67115351,6...","67093604,67096321,67103382,67111644,67115464,6...",0,C1orf141,cmpl,cmpl,"2,1,0,1,2,0,0,"
4,0,ENST00000371004.6,chr1,-,67092394,67134970,67092394,67092394,5,"67092394,67125751,67127165,67131141,67134929,","67096321,67125909,67127257,67131227,67134970,",0,C1orf141,none,none,"-1,-1,-1,-1,-1,"

In [2]:
TRgenes=UCSC_genedf[UCSC_genedf['name2'].str.startswith('TR')].copy()
TRgenes.head()

,#bin,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,score,name2,cdsStartStat,cdsEndStat,exonFrames
201,13,ENST00000648678.1,chr1,-,39838109,39883425,39865556,39883425,12,"39838109,39844100,39844530,39847219,39847547,3...","39841913,39844218,39844640,39847297,39847660,3...",0,TRIT1,cmpl,cmpl,"-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,"
202,13,ENST00000316891.10,chr1,-,39838109,39883504,39841743,39883491,11,"39838109,39844100,39844530,39847219,39847547,3...","39841913,39844218,39844640,39847297,39847660,3...",0,TRIT1,cmpl,cmpl,"1,0,1,1,2,1,2,0,0,0,0,"
203,13,ENST00000537440.5,chr1,-,39841021,39883504,39841743,39848001,10,"39841021,39844100,39844530,39847219,39847985,3...","39841913,39844218,39844640,39847297,39848097,3...",0,TRIT1,cmpl,cmpl,"1,0,1,1,0,-1,-1,-1,-1,-1,"
204,13,ENST00000441669.6,chr1,-,39841050,39883491,39841743,39883491,9,"39841050,39844100,39844530,39847219,39847547,3...","39841913,39844218,39844640,39847297,39847660,3...",0,TRIT1,cmpl,cmpl,"1,0,1,1,2,1,2,0,0,"
205,13,ENST00000462797.5,chr1,-,39841050,39883504,39844174,39883491,10,"39841050,39844100,39847219,39847547,39847985,3...","39841913,39844218,39847297,39847660,39848097,3...",0,TRIT1,cmpl,cmpl,"-1,1,1,2,1,2,0,0,0,0,"

In [3]:
TRgenes['padded_txStart']=TRgenes['txStart']-1000
TRgenes['padded_txEnd']=TRgenes['txEnd']+1000

In [4]:
chrs = ["chr" + str(i) for i in range(1, 23)]
chrs.append("chrX")
chrs.append("chrY")
chrs

['chr1',
 'chr2',
 'chr3',
 'chr4',
 'chr5',
 'chr6',
 'chr7',
 'chr8',
 'chr9',
 'chr10',
 'chr11',
 'chr12',
 'chr13',
 'chr14',
 'chr15',
 'chr16',
 'chr17',
 'chr18',
 'chr19',
 'chr20',
 'chr21',
 'chr22',
 'chrX',
 'chrY']

In [5]:
TRgenes=TRgenes[TRgenes['chrom'].isin(chrs)]

In [6]:
len(set(TRgenes['name2'].tolist()))

419

In [7]:
TRgenes.shape

(1938, 18)

In [8]:
TRgenes[TRgenes.duplicated(subset=['name2'])]

,#bin,name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds,score,name2,cdsStartStat,cdsEndStat,exonFrames,padded_txStart,padded_txEnd
202,13,ENST00000316891.10,chr1,-,39838109,39883504,39841743,39883491,11,"39838109,39844100,39844530,39847219,39847547,3...","39841913,39844218,39844640,39847297,39847660,3...",0,TRIT1,cmpl,cmpl,"1,0,1,1,2,1,2,0,0,0,0,",39837109,39884504
203,13,ENST00000537440.5,chr1,-,39841021,39883504,39841743,39848001,10,"39841021,39844100,39844530,39847219,39847985,3...","39841913,39844218,39844640,39847297,39848097,3...",0,TRIT1,cmpl,cmpl,"1,0,1,1,0,-1,-1,-1,-1,-1,",39840021,39884504
204,13,ENST00000441669.6,chr1,-,39841050,39883491,39841743,39883491,9,"39841050,39844100,39844530,39847219,39847547,3...","39841913,39844218,39844640,39847297,39847660,3...",0,TRIT1,cmpl,cmpl,"1,0,1,1,2,1,2,0,0,",39840050,39884491
205,13,ENST00000462797.5,chr1,-,39841050,39883504,39844174,39883491,10,"39841050,39844100,39847219,39847547,39847985,3...","39841913,39844218,39847297,39847660,39848097,3...",0,TRIT1,cmpl,cmpl,"-1,1,1,2,1,2,0,0,0,0,",39840050,39884504
206,13,ENST00000372818.5,chr1,-,39841050,39883506,39841743,39883491,10,"39841050,39844100,39844530,39847547,39847985,3...","39841913,39844218,39844640,39847660,39848097,3...",0,TRIT1,cmpl,cmpl,"1,0,1,2,1,2,0,0,0,0,",39840050,39884506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226579,967,ENST00000303434.8,chr22,+,50185916,50199598,50193060,50198519,10,"50185916,50193026,50193575,50194339,50194899,5...","50186001,50193093,50193654,50194506,50195040,5...",0,TRABD,cmpl,cmpl,"-1,0,0,1,0,0,0,2,1,2,",50184916,50200598
226580,967,ENST00000463233.1,chr22,+,50185917,50199595,50185917,50185917,9,"50185917,50193026,50193575,50194339,50194899,5...","50186001,50193093,50193654,50194506,50195040,5...",0,TRABD,none,none,"-1,-1,-1,-1,-1,-1,-1,-1,-1,",50184917,50200595
226581,967,ENST00000395827.5,chr22,+,50190597,50199475,50193060,50198519,10,"50190597,50193026,50193575,50194339,50194899,5...","50190648,50193093,50193654,50194506,50195040,5...",0,TRABD,cmpl,cmpl,"-1,0,0,1,0,0,0,2,1,2,",50189597,50200475
226583,967,ENST00000395829.1,chr22,+,50193013,50199569,50193060,50199128,10,"50193013,50193575,50194339,50194899,50197240,5...","50193093,50193654,50194506,50195040,50197351,5...",0,TRABD,cmpl,cmpl,"0,0,1,0,0,0,2,1,2,2,",50192013,50200569
226584,967,ENST00000472677.1,chr22,+,50196892,50198711,50196892,50196892,2,"50196892,50198344,","50198186,50198711,",0,TRABD,none,none,"-1,-1,",50195892,50199711

In [9]:
TRgenes.shape

(1938, 18)

In [10]:
outdf=TRgenes[['chrom','padded_txStart','padded_txEnd','name2']]
outdf.to_csv(UCSC_genetrack+"_TRprefix_names.txt",sep='\t',index=False)
outdf2=TRgenes[['chrom','padded_txStart','padded_txEnd']]
outdf2.to_csv(UCSC_genetrack+"_TRprefix.txt",sep='\t',index=False,header=False)