In [1]:
import numpy as np
import pandas as pd
import random as ran
import os

In [2]:
file_cn = 'Data/BL14_PhenoClass.txt'

transpose = True
header = None
index_col= True



lower_lim = 0.00372759
upper_lim = 0.00372759


'''
lower_lim = -3
upper_lim = -2
'''

repetition = 10

mix_num = 1

outfol = file_cn+"_from_"+str(lower_lim)+"_to_"+str(upper_lim)+'_proportions'

In [3]:
if transpose:
    data_cn = pd.read_csv(file_cn, sep='\t', index_col=0, header=header)
else:
    data_cn = pd.read_csv(file_cn, sep='\t', header=header)

df_cn = pd.DataFrame(data_cn)

if transpose:
    df_cn = df_cn.T

df_cn.columns

Index(['CD4', 'CD8', 'nB', 'NK', 'Mn', 'mNeu', 'm8', 'DC', 'Eo', 'Tr', 'm4',
       'Mg', 'Er', 'mB'],
      dtype='object', name=0)

In [4]:
def generate_list(cell_name, cell_list, val):
    length = len(cell_list)
    vals = np.zeros(length)
    r = [ran.random() for i in range(1,length)]
    s = sum(r)
    r = [ (i/s) * (100 - val) for i in r ]
    name_seen = False
    for i in range(length):
        if cell_list[i] != cell_name:
            if name_seen == False:
                vals[i] = r[i]
            elif name_seen:
                vals[i] = r[i - 1]
        elif cell_list[i] == cell_name:
            vals[i] = val
            name_seen = True
    return vals

In [5]:
mixtures = np.linspace(lower_lim, upper_lim, num=mix_num) * 100
#mixtures = np.logspace(lower_lim, upper_lim, num=mix_num) * 100
mixtures

array([0.372759])

In [6]:
os.mkdir(outfol)
df_final = pd.DataFrame(columns = list(df_cn.columns))

In [7]:
# os.mkdir(outfol)

for cell in list(df_cn.columns):
    df_out = pd.DataFrame(columns = list(df_cn.columns))
    for val in mixtures:
        for i in range(repetition):
            arr = generate_list(cell, list(df_cn.columns), val)
            while 0.0 in arr:
                arr = generate_list(cell, list(df_cn.columns), val)
            df_out.loc[len(df_out.index)] = arr
    display(df_out)
    df_out=df_out.round(6)
    df_final = pd.concat([df_final, df_out])
    
    
    df_out.to_csv(outfol + '/' + cell + '.txt', sep='\t', index=False)

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,0.372759,11.484439,10.912181,2.616940,0.325920,6.391040,13.205055,3.352242,8.545738,13.927723,6.298088,11.465778,9.246411,1.855685
1,0.372759,10.569796,14.139928,0.373471,13.398175,0.598979,4.283511,6.089767,7.215714,8.682645,2.554632,6.314864,13.942341,11.463419
2,0.372759,15.221885,14.972299,11.565403,10.294930,3.135881,2.858734,1.056210,2.777104,20.980839,1.726655,0.330726,4.814124,9.892452
3,0.372759,13.366729,10.353914,11.571508,1.240986,10.294362,0.800528,3.691269,9.776645,12.649909,9.108471,1.621432,14.526114,0.625375
4,0.372759,8.806800,10.432306,12.030454,11.498605,2.178215,3.545394,0.343147,11.211049,12.590190,6.445675,9.569888,0.599885,10.375634
5,0.372759,5.130677,5.373301,5.732494,14.385856,13.452353,10.472860,9.366430,0.951294,5.584048,3.672136,5.877699,7.102233,12.525859
6,0.372759,0.763911,5.227692,3.874897,5.317929,10.585044,4.688379,7.333368,8.537617,10.201021,13.352807,7.429906,13.913393,8.401278
7,0.372759,10.326216,7.643032,4.134926,1.418641,13.553417,7.929840,10.056256,0.378190,5.257792,11.383645,11.705599,9.091311,6.748377
8,0.372759,8.162950,8.203213,13.747429,0.383930,10.220803,3.004247,10.176932,1.474384,11.666634,10.934621,11.554160,9.752502,0.345434
9,0.372759,10.736853,12.146760,2.521541,2.490305,4.872774,2.593448,5.169430,11.416720,3.486301,12.572046,12.280848,10.104702,9.235512

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,3.734991,0.372759,5.117366,5.757584,2.505745,4.065194,6.540704,13.599799,13.542107,3.276439,12.731511,8.332243,7.956668,12.466892
1,5.123400,0.372759,7.545082,16.544552,1.980338,12.402269,13.001051,4.823517,8.520816,2.829466,5.126688,11.596216,7.433411,2.700436
2,3.242024,0.372759,11.835867,12.256730,12.496592,5.537114,2.139454,4.444800,11.358210,4.099913,8.520469,8.960442,5.000554,9.735072
3,6.661656,0.372759,12.196484,7.930328,10.579614,9.593962,6.491629,11.562547,3.174453,1.024526,6.946153,7.194080,3.886861,12.384947
4,10.990363,0.372759,10.409416,10.890137,4.927502,6.647960,5.506893,8.061469,10.937106,7.266056,3.810021,4.606561,6.305311,9.268447
5,0.168550,0.372759,8.740310,11.242201,2.839863,4.125252,6.557606,9.642477,12.775057,4.381688,13.822298,6.978829,10.604082,7.749027
6,0.825343,0.372759,16.031058,4.989873,5.805204,1.977998,0.751638,11.365152,22.891956,0.714963,9.761270,11.500452,2.227107,10.785226
7,3.162558,0.372759,7.727980,1.151589,14.440602,10.554798,9.042310,4.252901,12.464280,8.484506,1.659044,11.548554,11.401382,3.736736
8,12.918893,0.372759,11.260654,4.231787,2.851306,4.662241,6.055275,6.601200,11.412387,10.605746,7.274800,2.215269,11.241863,8.295821
9,3.954365,0.372759,13.683167,3.876822,7.361111,13.547472,11.558695,6.919344,4.084542,2.865690,9.784987,2.562537,14.853776,4.574733

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,7.517259,11.837526,0.372759,3.410569,7.845573,3.662663,14.686926,3.337618,8.714849,11.479834,11.638425,3.690643,1.017484,10.787872
1,3.641085,9.426573,0.372759,6.902899,6.763867,3.986845,13.391371,3.727178,13.589716,5.599592,1.795500,10.463204,9.392721,10.946688
2,7.537038,15.630360,0.372759,9.041933,19.466513,7.070592,2.894741,1.708384,3.219421,1.545568,1.851964,18.576782,3.023559,8.060387
3,14.106984,12.286173,0.372759,11.641174,9.795207,0.954147,4.311836,7.985001,7.377338,6.105470,2.052227,8.768987,10.572974,3.669725
4,12.562594,8.327372,0.372759,5.147274,1.881431,7.831267,1.059524,2.482195,8.928330,7.480841,11.281473,11.043111,9.836017,11.765809
5,8.630509,7.278024,0.372759,4.038059,11.486810,11.580556,13.359966,4.913018,1.491705,16.637200,14.030522,1.313566,4.666468,0.200839
6,15.957051,15.924963,0.372759,7.089415,5.175384,7.124238,9.087486,0.697182,16.867882,2.196402,5.996239,3.356201,8.607616,1.547183
7,4.724939,1.046779,0.372759,12.920710,9.153201,14.646478,4.792532,10.547362,9.155036,3.792387,14.039305,6.123911,6.691966,1.992634
8,6.703214,11.016777,0.372759,9.451612,4.046145,3.658772,10.909345,10.521576,8.989618,8.957373,10.260588,6.645644,0.396858,8.069718
9,7.944250,15.540046,0.372759,11.594379,10.342282,5.440240,7.592018,6.343901,4.189463,7.191142,3.612905,16.314642,0.294450,3.227523

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,7.504545,13.289109,4.436084,0.372759,3.297638,6.452805,10.406396,10.485739,8.512420,10.854460,1.319852,0.465939,9.402918,13.199336
1,2.253302,8.475351,0.609915,0.372759,7.778338,13.996248,3.559057,15.909686,1.317776,18.403552,0.065681,14.493394,12.195351,0.569591
2,12.660627,8.433307,9.749951,0.372759,0.581506,12.687089,6.359460,11.914239,11.175122,4.467261,10.353538,1.964638,1.234474,8.046029
3,5.873681,5.280953,7.879453,0.372759,10.204841,6.114641,13.511897,5.031798,4.948310,9.803136,12.448718,11.121165,7.317007,0.091641
4,2.958207,12.436187,9.535628,0.372759,13.105342,11.515247,1.475130,9.568209,2.479883,7.069461,2.150287,11.269363,14.474850,1.589450
5,8.006266,16.112587,5.876668,0.372759,8.075994,6.958107,8.889899,1.302391,4.168798,6.586832,3.351186,2.334155,17.726635,10.237723
6,10.457716,1.749097,6.865915,0.372759,6.326827,11.356743,0.192571,4.399127,11.957773,12.494422,11.352936,7.344215,5.533976,9.595923
7,12.657104,1.664378,9.189592,0.372759,13.049338,7.478787,10.047566,10.905909,12.762191,2.458831,6.469436,3.937727,3.015559,5.990825
8,6.691841,6.865444,11.849355,0.372759,8.803400,4.136386,11.436925,6.542916,6.787908,4.690680,11.427170,6.519348,4.764207,9.111661
9,6.632296,9.632320,7.703529,0.372759,3.507736,11.162667,10.326629,3.945020,10.803063,9.750067,10.091596,9.198006,1.248395,5.625917

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,12.693555,11.510491,8.599925,0.519943,0.372759,4.042557,9.636486,10.792505,11.497363,5.899986,10.068170,9.855928,0.217819,4.292513
1,1.612616,12.993474,4.082358,11.942602,0.372759,6.897477,0.316951,6.570477,5.626028,9.672104,13.204637,5.092395,10.008072,11.608050
2,2.626783,11.134014,10.683499,3.279521,0.372759,11.858923,9.264012,12.691039,2.648479,8.943432,2.392546,8.328616,12.304164,3.472212
3,3.393118,14.957028,5.415077,6.030211,0.372759,12.641742,15.435142,1.335442,0.168821,14.504465,2.414681,0.843842,13.928572,8.559100
4,14.370996,6.421216,5.953266,2.934094,0.372759,3.307439,1.677082,7.926384,15.360322,1.507402,10.958311,14.325035,9.402904,5.482790
5,7.858945,10.985303,7.837288,12.745777,0.372759,11.086070,11.891187,3.395391,1.310891,6.811064,8.368368,10.452040,4.307902,2.577016
6,10.466421,1.389990,1.870705,12.744442,0.372759,12.237525,14.216794,11.010258,0.376058,12.429932,2.421330,8.972435,5.521566,5.969785
7,3.381931,7.338230,3.725453,10.712843,0.372759,3.611843,13.766006,7.164948,8.995797,0.380398,4.140024,13.646415,13.461380,9.301971
8,3.224768,0.855316,5.611892,10.049710,0.372759,12.285358,4.576680,4.488938,9.754639,12.417171,8.076188,7.092950,8.849447,12.344184
9,4.632577,2.855469,7.762482,1.677560,0.372759,4.054257,0.630500,1.144486,6.328148,4.728263,16.209164,14.003038,19.205527,16.395769

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,8.633789,9.207846,10.816069,1.432298,3.899507,0.372759,19.685363,0.723965,8.324359,0.237032,13.699804,5.404126,5.740500,11.822583
1,8.846536,11.659887,13.917892,4.055963,10.056243,0.372759,2.128162,1.981986,14.055968,1.604047,7.716510,9.851612,8.139657,5.612780
2,12.763833,10.722492,12.839138,2.565417,10.947521,0.372759,12.142866,0.757315,13.373016,6.607588,4.884814,0.490473,10.778346,0.754423
3,9.291853,14.297252,3.662444,2.941782,3.471183,0.372759,10.938406,3.075826,13.208371,7.684832,9.642047,11.236158,6.872311,3.304776
4,7.226358,5.634137,14.102037,12.039688,4.194040,0.372759,7.776022,7.004334,0.562152,5.429023,3.394929,14.873542,2.107496,15.283484
5,9.520972,5.723213,11.492175,6.079822,6.337035,0.372759,8.535755,10.851274,9.930766,7.556283,5.767752,4.677907,1.353343,11.800944
6,4.375650,9.977305,3.219375,10.839072,6.724891,0.372759,4.768844,7.264937,14.111021,14.683682,6.365440,2.977690,2.647873,11.671460
7,15.628513,10.369971,6.345587,4.097714,4.353571,0.372759,11.899137,14.273242,4.488895,3.349677,6.566825,4.125639,5.933014,8.195457
8,1.472414,11.340691,5.628591,1.628346,14.120398,0.372759,0.742786,10.284802,13.578431,11.110387,2.646809,9.291860,3.608193,14.173533
9,8.097256,6.913265,0.508306,10.551318,8.286528,0.372759,1.545172,12.667456,13.649528,8.405563,0.463816,12.230784,9.636202,6.672047

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,17.094050,12.493661,6.032670,11.205975,19.629978,0.013680,0.372759,5.082856,4.864910,7.694781,1.463084,6.951441,0.715826,6.384331
1,17.315752,1.378035,2.079054,0.209394,10.386403,0.011530,0.372759,7.413864,16.527902,12.291618,2.850704,16.032936,4.747953,8.382094
2,6.897464,4.903620,12.164699,13.699150,3.969824,11.983899,0.372759,8.081913,2.350677,14.937887,9.088240,0.581734,10.741724,0.226409
3,12.078277,5.388510,15.813807,10.279808,3.683189,7.053637,0.372759,11.803116,7.024932,6.589116,7.118369,3.564892,2.187589,7.042000
4,11.435557,8.733801,2.766759,0.259699,3.367238,13.978669,0.372759,12.046361,10.082615,0.619437,14.537362,0.022086,5.438476,16.339180
5,9.032751,5.979961,3.914005,0.727340,15.115942,14.818178,0.372759,8.887535,0.236533,4.683461,4.364968,8.021150,9.744496,14.100919
6,9.144216,2.938175,14.756200,1.766740,4.191575,6.792297,0.372759,6.334444,5.728624,10.203262,16.594897,8.466219,6.417024,6.293569
7,9.428924,9.897446,11.646139,12.324530,12.153260,2.058350,0.372759,0.590805,5.810043,2.666618,4.443670,9.649042,10.577808,8.380608
8,6.770834,9.363736,7.344800,5.416344,14.914270,14.539968,0.372759,13.120529,1.913455,0.341359,7.352568,14.775093,2.716562,1.057724
9,8.905743,13.599990,9.177207,7.986190,5.714099,11.671939,0.372759,2.327843,0.327207,6.546727,12.279904,6.922451,7.163736,7.004204

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,1.768043,8.308307,3.198714,5.173288,14.190587,10.012252,1.049866,0.372759,12.908664,5.682399,5.454491,10.554738,9.905538,11.420354
1,13.031558,5.278760,10.448974,6.913384,12.797406,1.034807,10.289122,0.372759,12.568546,3.873827,5.202799,14.078394,3.765588,0.344076
2,2.859777,0.515715,18.302727,9.603325,0.842751,5.313081,7.486417,0.372759,14.365993,11.483823,1.302356,12.288068,2.106622,13.156587
3,0.356158,6.079915,14.546323,15.731961,3.052780,8.675127,8.688664,0.372759,13.843176,2.319841,10.576208,6.315818,2.589988,6.851282
4,8.574394,9.238231,9.961619,1.332952,9.767686,2.177935,5.212807,0.372759,10.299141,10.044000,9.845785,4.690566,9.242618,9.239507
5,6.407963,8.895314,14.350307,3.515428,11.417968,8.402918,7.389342,0.372759,8.068191,9.728015,1.290379,2.831299,7.062659,10.267457
6,13.051107,8.112619,6.493571,10.823040,3.686134,3.872990,11.338837,0.372759,0.625939,10.836138,12.909622,4.194754,11.682734,1.999754
7,1.908927,2.695750,9.490993,2.310203,4.846621,11.625552,5.802039,0.372759,14.028114,4.021446,14.769791,8.836769,6.334062,12.956975
8,9.197588,3.153122,8.471341,3.165250,14.919099,5.405648,7.467579,0.372759,13.240112,10.536084,11.239039,12.144088,0.462996,0.225297
9,12.104957,10.134273,9.067572,10.780304,6.478345,12.488195,8.463300,0.372759,7.148483,1.386131,4.155181,5.860008,6.227765,5.332727

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,6.846144,1.918245,4.048339,15.585131,3.307701,14.895029,6.383950,5.210831,0.372759,5.339389,9.493064,5.120153,9.455671,12.023593
1,0.233883,5.450049,6.736457,10.287171,9.596937,7.916515,9.374873,9.234887,0.372759,9.044901,6.706435,10.035479,3.849254,11.160401
2,14.311544,3.955310,8.150630,10.299288,11.519561,3.019299,11.317447,6.915702,0.372759,3.424205,5.540322,0.371956,12.105932,8.696046
3,6.551618,10.740853,7.428809,10.745920,11.678124,1.096228,10.034364,1.834840,0.372759,7.248860,6.798662,7.719533,9.441082,8.308347
4,9.657166,0.797162,5.553954,16.998377,4.875703,12.259885,11.840998,12.559262,0.372759,14.403311,2.294169,1.103884,1.612371,5.670999
5,4.211553,9.584286,7.422542,6.903533,6.383796,11.183656,9.955937,9.930463,0.372759,5.117496,8.036998,5.527707,5.803444,9.565830
6,10.041549,9.563641,0.967069,6.763747,6.284179,11.574029,13.041829,11.267631,0.372759,2.076571,6.535101,7.965020,10.576357,2.970518
7,10.855511,7.973941,10.194369,5.262909,4.590326,11.737590,6.172281,1.143128,0.372759,10.638247,4.047509,6.161256,10.360555,10.489618
8,4.593175,5.875105,6.914621,11.325238,7.132304,7.170550,12.317036,6.315741,0.372759,7.405729,6.996316,6.910961,9.586782,7.083683
9,14.430472,1.650777,6.489810,6.667643,1.690726,11.634160,15.430142,3.386259,0.372759,11.729508,12.511765,3.486011,5.857798,4.662171

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,6.749030,5.617783,5.462319,8.499640,7.050328,4.273269,7.968390,1.529764,3.832339,0.372759,14.261212,12.425306,10.312196,11.645665
1,13.824865,12.647322,6.443614,6.936662,4.395068,12.272217,5.309507,5.090556,6.576517,0.372759,6.862704,2.054546,4.809729,12.403934
2,5.839982,1.313291,6.214564,12.101507,5.719976,6.812726,2.042746,3.418968,11.684658,0.372759,13.290307,6.634938,13.673279,10.880298
3,9.034679,11.113896,0.448198,4.549978,7.948381,1.676236,15.336800,10.015908,3.279989,0.372759,12.381845,7.660004,2.234525,13.946802
4,0.788240,12.013473,11.959432,10.782804,3.260325,2.163806,2.689406,12.174449,13.683480,0.372759,5.003905,2.650627,9.314883,13.142413
5,13.755297,3.976909,0.227237,5.420172,9.001463,7.295254,14.271061,4.479654,3.535838,0.372759,10.159491,13.066737,6.815955,7.622171
6,9.061509,4.916297,4.996225,3.148185,14.569197,16.653301,0.677244,3.129219,8.867626,0.372759,1.755974,17.730122,12.626617,1.495723
7,7.496699,11.581724,8.228250,5.723701,1.848660,10.345254,8.821125,2.299426,12.507374,0.372759,8.092514,10.741618,1.061223,10.879674
8,3.820754,12.786734,11.931754,10.454670,2.608663,10.130807,2.993098,15.503479,7.281654,0.372759,9.059332,5.857260,3.738509,3.460526
9,2.474114,8.276961,11.326616,12.526255,9.239539,11.637256,6.953071,10.556180,7.045457,0.372759,3.843556,1.675869,0.702533,13.369834

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,3.459811,15.834705,13.399581,3.712189,18.129368,13.530387,2.169889,1.262264,6.791968,12.827551,0.372759,0.301879,5.286731,2.920918
1,6.447111,9.719701,0.891908,10.562872,11.012608,2.311985,6.507001,6.691928,9.370624,2.089170,0.372759,14.890269,12.241837,6.890227
2,1.432585,19.893990,7.798000,3.678434,0.311439,1.784677,9.985165,3.162995,20.233664,13.244278,0.372759,7.309320,5.050678,5.742016
3,5.087917,0.820841,14.148834,1.473649,7.628776,18.204518,10.430860,9.370754,10.432108,4.948054,0.372759,12.185981,1.299726,3.595222
4,2.150773,10.270424,4.123031,7.810812,5.165774,5.061575,9.915086,6.836571,15.126550,1.356159,0.372759,3.404715,15.360367,13.045405
5,3.195049,12.807449,0.249967,10.423262,5.194032,10.230234,2.208806,13.580949,0.256158,11.047695,0.372759,2.457444,10.513114,17.463082
6,15.140442,11.658552,11.033455,0.264308,5.791991,13.376178,13.854127,12.755400,2.889502,4.938176,0.372759,2.948403,1.920172,3.056535
7,10.697153,9.232601,8.152199,10.573015,7.662927,9.927616,4.510399,2.154643,2.064971,12.832712,0.372759,0.735638,9.679616,11.403751
8,4.425103,1.394826,10.900104,3.028347,10.389877,13.217285,10.827652,2.910701,3.149336,7.137584,0.372759,13.470878,14.551661,4.223887
9,9.790012,13.595996,6.516805,8.180762,10.727357,0.771890,0.165623,9.722439,7.736357,10.626303,0.372759,5.678832,5.237406,10.877460

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,12.226355,11.405852,15.857377,11.781564,5.733220,10.339459,2.079669,10.473113,3.112009,8.670280,1.407672,0.372759,6.376667,0.164004
1,1.146902,9.661749,13.718334,4.878698,7.569533,10.522521,2.252434,1.079131,12.665554,13.188679,7.733365,0.372759,4.414605,10.795737
2,5.144762,0.756017,10.938171,8.912493,3.181787,7.524291,9.874251,8.219076,6.200376,10.715466,12.069960,0.372759,11.949857,4.140735
3,7.682459,9.643287,9.252705,3.616187,3.899950,9.878441,6.560649,11.829796,3.416818,10.387603,7.124471,0.372759,9.023167,7.311707
4,12.998976,3.861319,6.888490,4.633076,14.617077,12.122892,6.290376,5.884086,7.146634,11.951107,2.573468,0.372759,3.469366,7.190374
5,2.488448,7.747372,0.577649,5.891542,12.571337,9.666400,6.144064,7.901659,11.706304,7.347850,7.167706,0.372759,10.318852,10.098058
6,6.432774,0.607174,1.587648,3.551357,11.562316,8.249183,5.487683,1.338747,10.904423,4.938688,17.416249,0.372759,9.266384,18.284617
7,5.599630,7.583351,13.327404,14.354729,2.931662,9.433959,14.940271,4.228582,2.866872,5.371550,8.339787,0.372759,5.981336,4.668108
8,0.238881,7.379415,7.076690,14.631023,6.142299,7.900207,10.938043,0.455760,16.162424,15.266978,2.311864,0.372759,8.444501,2.679155
9,0.629174,17.673428,0.822715,3.821239,14.422290,1.237866,16.384178,2.606232,10.778908,2.502551,8.059397,0.372759,15.340611,5.348653

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,11.845969,5.343423,3.897311,12.430526,3.329198,3.955725,8.786610,2.096088,7.512758,12.087698,9.045472,7.029802,0.372759,12.266662
1,14.401651,7.553697,12.537421,14.143399,2.714190,3.394016,3.450338,0.706193,16.389478,3.206461,0.609401,15.031295,0.372759,5.489702
2,11.831810,11.605744,4.639492,9.465834,2.944320,6.688325,3.850483,12.193249,9.554574,8.237886,3.307949,7.092905,0.372759,8.214671
3,3.265887,9.761321,11.865676,8.574545,7.359492,8.990480,5.763438,4.181231,8.122699,10.470463,8.092152,11.196175,0.372759,1.983682
4,4.039081,6.465045,10.889248,5.313221,7.653791,2.053911,13.788276,3.999491,14.218049,7.341280,0.019036,15.074885,0.372759,8.771928
5,1.886302,7.185695,15.646598,0.618407,15.229325,13.997367,1.465019,12.179929,12.532901,12.428236,1.564086,3.057293,0.372759,1.836083
6,5.544842,2.879711,2.836719,4.485938,10.520131,7.678210,11.717594,8.958766,7.683246,10.766896,11.576212,10.030886,0.372759,4.948091
7,13.155120,0.946102,12.035763,13.699905,3.698011,11.364012,5.457531,3.253486,6.489903,2.611616,9.473275,15.127266,0.372759,2.315253
8,14.137940,7.223953,7.901870,4.252716,4.685615,1.452169,12.462425,8.719062,2.021230,14.651094,14.320839,0.153381,0.372759,7.644947
9,6.950895,11.850978,6.416274,12.186031,12.499417,8.280729,2.596365,11.562863,6.566491,3.798973,3.558115,1.980148,0.372759,11.379962

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,3.087528,2.379231,0.161624,7.053580,8.412845,6.399896,12.775906,7.991208,13.217559,15.184403,1.441015,12.271600,9.250846,0.372759
1,6.186980,10.977919,6.121138,5.902600,10.329674,7.302512,12.203039,4.624940,9.753161,11.223688,1.812759,11.052642,2.136188,0.372759
2,5.884443,9.589553,12.290592,2.150541,14.186323,8.258755,11.302823,1.572241,7.239484,9.489950,2.654976,10.552763,4.454797,0.372759
3,11.421510,15.067061,2.784616,16.031793,14.603885,13.003322,1.284086,0.600992,2.339320,5.353256,7.974324,0.509323,8.653753,0.372759
4,4.322455,1.823674,12.526883,8.647930,10.405642,12.856713,3.523194,8.058536,9.388859,6.898020,1.616935,3.163721,16.394679,0.372759
5,14.864356,1.335980,8.672690,15.584490,1.100157,3.875056,5.551218,0.880214,1.492036,5.339192,12.395994,12.383731,16.152125,0.372759
6,11.213434,7.221901,4.133138,0.492101,7.311801,12.628471,1.138153,12.250965,12.916983,8.725138,14.056380,3.297164,4.241613,0.372759
7,9.485585,2.698034,12.983545,8.629306,11.994453,3.767359,5.113301,3.716231,12.825117,7.625048,3.079932,11.766372,5.942957,0.372759
8,8.180589,1.850714,6.067854,9.366265,11.087057,6.757307,8.437826,11.277893,8.887255,4.351064,6.847182,9.364763,7.151470,0.372759
9,6.334810,10.012655,0.736833,9.762752,11.163926,12.356114,6.020200,7.221632,3.044138,10.324483,12.903568,6.557471,3.188660,0.372759

In [8]:
df_final.head()

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,0.372759,11.484439,10.912181,2.616940,0.325920,6.391040,13.205055,3.352242,8.545738,13.927723,6.298088,11.465778,9.246411,1.855685
1,0.372759,10.569796,14.139928,0.373471,13.398175,0.598979,4.283511,6.089767,7.215714,8.682645,2.554632,6.314864,13.942341,11.463419
2,0.372759,15.221885,14.972299,11.565403,10.294930,3.135881,2.858734,1.056210,2.777104,20.980839,1.726655,0.330726,4.814124,9.892452
3,0.372759,13.366729,10.353914,11.571508,1.240986,10.294362,0.800528,3.691269,9.776645,12.649909,9.108471,1.621432,14.526114,0.625375
4,0.372759,8.806800,10.432306,12.030454,11.498605,2.178215,3.545394,0.343147,11.211049,12.590190,6.445675,9.569888,0.599885,10.375634

In [9]:
df_final.to_csv(outfol + '/combined.txt', sep='\t', index=False)