In [1]:
import numpy as np
import pandas as pd
import random as ran
import os

In [2]:
file_cn = 'Data/BL14_PhenoClass.txt'

transpose = True
header = None
index_col= True



lower_lim = 0.01
upper_lim = 0.1


'''
lower_lim = -5
upper_lim = -2
'''

repetition = 3

mix_num = 3

outfol = file_cn+"_from_"+str(lower_lim)+"_to_"+str(upper_lim)+'_proportions'

In [3]:
if transpose:
    data_cn = pd.read_csv(file_cn, sep='\t', index_col=0, header=header)
else:
    data_cn = pd.read_csv(file_cn, sep='\t', header=header)

df_cn = pd.DataFrame(data_cn)

if transpose:
    df_cn = df_cn.T

df_cn.columns

Index(['CD4', 'CD8', 'nB', 'NK', 'Mn', 'mNeu', 'm8', 'DC', 'Eo', 'Tr', 'm4',
       'Mg', 'Er', 'mB'],
      dtype='object', name=0)

In [4]:
def generate_list(cell_name, cell_list, val):
    length = len(cell_list)
    vals = np.zeros(length)
    r = [ran.random() for i in range(1,length)]
    s = sum(r)
    r = [ (i/s) * (100 - val) for i in r ]
    name_seen = False
    for i in range(length):
        if cell_list[i] != cell_name:
            if name_seen == False:
                vals[i] = r[i]
            elif name_seen:
                vals[i] = r[i - 1]
        elif cell_list[i] == cell_name:
            vals[i] = val
            name_seen = True
    return vals

In [5]:
mixtures = np.linspace(lower_lim, upper_lim, num=mix_num) * 100
#mixtures = np.logspace(lower_lim, upper_lim, num=mix_num) * 100
mixtures

array([ 1. ,  5.5, 10. ])

In [6]:
os.mkdir(outfol)
df_final = pd.DataFrame(columns = list(df_cn.columns))

In [7]:
# os.mkdir(outfol)

for cell in list(df_cn.columns):
    df_out = pd.DataFrame(columns = list(df_cn.columns))
    for val in mixtures:
        for i in range(repetition):
            arr = generate_list(cell, list(df_cn.columns), val)
            while 0.0 in arr:
                arr = generate_list(cell, list(df_cn.columns), val)
            df_out.loc[len(df_out.index)] = arr
    display(df_out)
    df_out=df_out.round(6)
    df_final = pd.concat([df_final, df_out])
    
    
    df_out.to_csv(outfol + '/' + cell + '.txt', sep='\t', index=False)

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,1.0,4.242964,9.727991,2.487640,9.276884,14.262146,10.511050,2.714504,2.988385,11.723815,1.664164,12.540410,7.565846,9.294202
1,1.0,16.946883,4.901470,5.793087,6.941020,6.366080,5.600586,3.245494,10.738783,8.994274,3.969390,4.417968,7.698795,13.386170
2,1.0,7.310348,7.503049,8.641615,2.621892,6.432013,6.888139,7.257567,12.078934,13.761323,8.074576,11.290380,2.004406,5.135761
3,5.5,7.307491,5.512576,8.871160,8.575521,7.412665,9.197438,8.643014,5.346761,1.247877,11.123711,8.991908,12.083755,0.186123
4,5.5,8.022166,1.071140,9.539095,3.978240,8.826514,10.534063,8.330669,2.256654,1.802282,5.335602,12.678101,9.497714,12.627760
5,5.5,7.175427,3.765750,1.017045,7.108360,1.877298,9.489886,2.781227,4.606862,2.598467,13.458196,15.014918,14.751706,10.854858
6,10.0,1.986040,11.145764,2.745721,1.053944,1.923531,12.582386,5.564909,4.577422,12.938023,0.817467,14.508783,8.122394,12.033618
7,10.0,0.151716,7.696677,11.109541,12.158203,6.578982,12.570452,1.184333,0.680693,4.209910,1.564685,15.084718,4.863206,12.146884
8,10.0,5.321041,0.321907,7.873527,9.899479,8.407715,2.388655,4.419815,10.944846,1.293273,10.025135,9.096309,11.635640,8.372658

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,9.370433,1.0,7.418696,9.378475,1.782143,13.660470,13.484181,10.290610,4.933858,7.158625,0.322388,12.360975,2.810362,6.028785
1,2.273204,1.0,10.229954,13.731376,3.360931,7.312835,8.138450,18.694348,3.502308,6.538464,13.605185,0.519008,0.036495,11.057444
2,8.396312,1.0,18.201848,11.061141,4.163168,12.592404,9.903538,3.077790,15.949497,0.075568,2.657022,9.376696,0.690654,2.854362
3,2.588132,5.5,6.259576,4.893844,13.550552,4.715464,5.518296,13.579148,13.600503,4.467441,8.577078,1.177613,6.834289,8.738063
4,5.129843,5.5,13.820237,12.043999,13.443346,7.687956,2.946075,1.331103,12.015421,5.086179,6.891759,10.784073,2.561539,0.758470
5,8.980354,5.5,2.999720,6.701608,5.216556,10.403470,7.493117,9.645346,5.775876,6.269414,8.261976,10.692183,3.357524,8.702856
6,6.990630,10.0,0.647198,5.653086,9.151755,0.079049,9.523720,17.690854,0.329730,1.596851,9.233298,19.136566,7.844646,2.122617
7,11.755048,10.0,3.225582,13.083520,8.312746,6.321034,11.601788,5.627964,9.592777,1.547497,2.339880,11.816526,2.641276,2.134361
8,8.945106,10.0,0.170673,1.668574,6.764505,0.453704,12.216758,11.912727,8.387463,11.976366,5.281345,6.871047,7.392411,7.959321

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,3.295161,4.580049,1.0,1.359391,12.827471,5.538433,10.336652,10.206725,3.601296,8.051077,11.865906,10.119471,12.168229,5.050141
1,9.266842,12.588726,1.0,2.683738,16.982246,12.998226,5.905893,1.890138,10.739132,3.388759,1.741554,10.041361,1.017328,9.756057
2,14.509085,14.994802,1.0,0.220233,3.089440,8.366432,5.251955,1.914546,11.588050,11.081495,10.379763,1.372939,14.035571,2.195691
3,4.991419,7.329509,5.5,9.138012,10.437639,0.394214,10.452553,11.224676,4.295218,6.963467,9.790298,1.016634,11.068783,7.397578
4,11.433369,2.681045,5.5,1.230665,11.309811,3.800530,3.491410,6.704281,1.585588,13.225328,13.849515,8.517771,4.241352,12.429335
5,9.291061,9.380228,5.5,8.397164,5.666915,17.021607,5.464640,14.952041,5.583669,2.835502,5.438688,7.843749,2.100868,0.523869
6,7.158792,2.362029,10.0,1.681329,2.720059,14.137051,14.973703,1.604962,1.598041,6.819914,5.052716,5.575387,15.031175,11.284843
7,5.242748,6.292082,10.0,3.882970,7.096825,2.993047,4.486838,3.806993,7.298185,11.676408,6.948210,7.353771,15.615428,7.306495
8,10.067586,8.881469,10.0,3.912171,8.893050,1.950679,8.850709,7.154077,1.117515,7.911909,7.620131,10.934862,5.089309,7.616533

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,9.647467,7.599545,6.741121,1.0,4.479219,7.137387,1.359007,12.686264,8.512038,9.888478,13.428730,1.989239,7.974811,7.556694
1,11.224814,15.400971,7.029111,1.0,8.873739,10.461252,1.690333,0.146608,10.590382,4.562564,15.066727,0.337531,0.639417,12.976550
2,13.654359,1.410379,13.169333,1.0,11.110746,0.307417,8.358478,5.463893,11.407605,10.276076,7.143983,3.448891,6.130152,7.118688
3,12.538552,7.426816,12.089750,5.5,11.461920,9.137309,0.931143,11.533750,1.113625,1.508462,10.655435,6.994405,7.639778,1.469055
4,3.276251,7.429555,3.363983,5.5,13.249475,8.226654,13.120322,3.566719,5.125521,11.695036,14.540856,8.472160,0.928078,1.505390
5,4.901966,4.684748,11.750927,5.5,9.803352,13.157561,0.073193,12.190084,2.540122,7.643607,0.896399,11.622345,5.349460,9.886236
6,11.519753,0.050191,7.155062,10.0,3.092042,7.850467,10.417604,10.895759,1.132124,9.599389,2.202737,3.706011,13.472681,8.906180
7,1.867178,8.206875,5.929401,10.0,12.232477,2.458658,11.181023,8.166334,10.988958,11.603611,3.538351,3.224081,0.922315,9.680738
8,1.734474,7.439662,8.160742,10.0,11.751929,4.255497,6.741291,11.594949,6.607779,8.823513,8.783611,6.809541,3.857760,3.439251

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,12.203182,14.131049,9.813854,0.588129,1.0,12.668348,12.455821,2.885432,3.419650,0.296392,3.974963,3.232017,15.035965,8.295196
1,14.083713,8.038749,12.058441,3.987271,1.0,4.204431,10.564430,3.810270,7.857347,13.713156,7.947421,1.082369,1.553602,10.098800
2,3.576814,10.990868,11.422782,10.794280,1.0,11.518895,10.709967,7.959459,5.243046,8.085635,4.135165,0.900952,11.416312,2.245827
3,12.921567,10.769201,1.413338,3.557287,5.5,7.755523,13.126819,3.291574,0.857646,7.997895,2.531195,8.261982,13.451452,8.564521
4,9.271849,5.601095,7.981434,2.968721,5.5,9.681597,6.568393,7.215960,8.100887,6.231917,6.412472,8.274789,7.771062,8.419824
5,6.123787,1.964364,13.245037,8.516219,5.5,1.928547,1.768058,0.671485,13.596985,6.718834,9.843019,9.920229,8.099779,12.103657
6,8.092601,3.956695,5.697459,10.551839,10.0,3.381015,8.400888,7.666161,4.184829,8.636963,9.834120,6.108042,2.175910,11.313479
7,0.987030,4.993503,4.000873,10.509043,10.0,0.559141,7.237165,3.693975,0.870838,15.707713,18.461898,0.980582,19.813566,2.184675
8,6.843884,6.473365,4.092928,1.005742,10.0,11.478053,11.820673,5.779144,12.588313,12.939972,0.692811,2.677761,3.882833,9.724520

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,11.059927,5.551784,13.492034,4.725203,8.754215,1.0,7.327836,6.467822,4.378696,7.985188,6.005108,14.003266,7.464638,1.784283
1,18.444784,16.366258,3.508628,8.124765,7.095109,1.0,5.439835,0.758129,6.158167,3.535254,0.012933,1.441251,14.573388,13.541499
2,7.519258,3.854053,9.482448,12.406491,9.502391,1.0,2.676664,9.650831,7.109825,1.560263,6.047027,8.697726,8.768053,11.724968
3,4.099161,2.307507,8.444460,11.209140,10.864411,5.5,1.881525,10.907040,6.244041,1.404798,11.617758,9.662147,7.687678,8.170334
4,8.957194,6.676663,5.989868,7.316044,10.830524,5.5,9.732442,3.111600,0.849515,10.263378,13.058327,12.874989,1.519155,3.320301
5,5.118346,13.881510,13.482477,5.278290,7.378583,5.5,6.303262,10.608331,5.347923,1.568478,3.857750,6.419113,8.719154,6.536784
6,2.325358,8.647102,13.474476,4.467794,2.418467,10.0,3.553738,13.963533,4.073147,11.823238,1.463470,6.388259,14.464566,2.936854
7,4.001611,5.413437,7.218439,10.297653,7.152869,10.0,4.315510,15.096202,3.756604,1.719891,12.902634,11.396688,3.625054,3.103409
8,5.778754,0.604705,8.958231,3.883359,6.183703,10.0,3.903124,2.736660,10.675837,11.507289,8.544604,11.525223,9.226178,6.472334

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,12.809003,9.437098,15.969253,5.502394,5.438264,1.259374,1.0,8.042550,10.881600,9.582055,7.812249,3.853194,0.182798,8.230168
1,1.192143,5.672019,8.186048,13.772323,9.208828,6.685036,1.0,3.763430,1.898236,9.207989,11.365456,13.200556,9.509344,5.338591
2,0.844257,2.558304,14.362668,0.183626,5.647099,3.422370,1.0,6.938082,9.323987,15.413552,0.881814,13.219587,7.284982,18.919670
3,4.590228,10.899777,1.001033,8.557517,0.303339,11.698842,5.5,9.678260,12.453444,4.782232,2.154663,11.053251,8.811649,8.515764
4,9.206321,0.311748,4.869386,14.151423,16.263144,1.945556,5.5,8.262236,0.944957,5.712386,14.254399,3.838282,12.391954,2.348206
5,5.539325,10.895661,6.655836,4.801560,4.593003,5.764788,5.5,11.869039,11.104430,3.448341,8.173348,0.410693,9.925345,11.318631
6,11.954922,1.703604,5.861954,5.606912,8.102455,6.930202,10.0,7.099476,5.521199,9.811923,8.815708,9.651828,6.099335,2.840481
7,13.206492,14.185301,3.330176,6.025381,6.002091,3.173878,10.0,1.940665,13.425438,2.380684,6.456844,4.905070,10.832142,4.135838
8,5.384984,5.481201,8.797720,1.818473,10.427975,0.845366,10.0,4.496980,4.632036,11.482472,12.237444,11.301272,5.627992,7.466085

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,5.672210,8.984589,2.782955,3.415442,9.530337,7.677593,11.097130,1.0,9.923240,5.741806,6.501194,1.824341,12.700776,13.148387
1,2.380504,10.116829,1.080797,6.269202,13.498912,3.690399,9.658672,1.0,11.626071,11.282008,7.119411,10.956020,11.118082,0.203093
2,13.635033,8.665164,9.612510,13.090548,13.844551,1.724863,3.647877,1.0,10.702092,4.075216,6.957665,7.814654,2.780165,2.449664
3,2.075240,4.737194,15.659517,15.103350,1.261039,1.464952,2.582003,5.5,18.099923,7.630654,3.955778,7.370632,3.834613,10.725105
4,12.771380,3.778067,6.167454,2.707219,6.782985,13.430532,0.937860,5.5,5.894295,0.708758,13.825476,4.141068,12.740433,10.614474
5,0.850591,8.820878,4.124892,9.685633,8.349367,13.048895,1.274694,5.5,4.593718,2.160370,13.270264,10.811996,5.131551,12.377151
6,11.921119,12.463329,5.092209,11.787516,5.788939,2.947583,1.008793,10.0,6.498764,8.400378,5.323716,5.340025,1.312049,12.115579
7,10.685673,0.353236,5.204203,2.473141,13.630129,8.222708,1.533402,10.0,0.769722,5.300631,6.492615,10.643972,14.677739,10.012828
8,13.168543,5.318501,11.062033,2.140778,4.970759,0.552748,9.334069,10.0,3.311376,13.859550,5.228622,1.320326,8.798734,10.933960

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,9.566312,10.251024,3.587918,4.462600,5.286037,9.833641,9.327284,4.029085,1.0,6.578361,11.988218,1.705886,10.296682,12.086951
1,11.010333,7.472155,1.895586,1.112167,2.112317,2.166779,2.996123,13.081933,1.0,9.789176,9.514216,13.891521,13.646260,10.311434
2,8.715945,2.524016,9.371483,9.481400,5.883811,1.227604,12.975235,10.553522,1.0,11.854727,8.064276,10.484456,3.253561,4.609964
3,5.673037,11.055089,0.701632,10.795894,9.565687,3.892708,1.462389,9.292827,5.5,8.277090,10.802432,8.996450,3.337536,10.647230
4,9.479557,8.063596,11.184166,1.768425,12.594435,0.689821,9.116288,11.493854,5.5,2.386638,7.113428,4.957121,3.968221,11.684450
5,2.835332,4.026225,3.260158,12.820863,10.271185,10.976181,4.260270,13.244733,5.5,11.658679,4.046237,7.545971,1.813507,7.740659
6,4.227268,8.165225,7.975056,6.610875,10.690659,4.913694,7.866378,9.137029,10.0,9.715605,0.856192,11.437475,6.253185,2.151357
7,6.780789,8.575897,2.661091,3.009455,8.913743,12.531701,2.487034,8.652021,10.0,9.480326,12.218304,1.540224,8.491877,4.657538
8,9.135184,0.571083,7.051062,2.714571,3.582425,9.258720,10.107907,10.909096,10.0,9.934644,11.617387,3.425078,5.012040,6.680804

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,10.590687,2.548738,11.467164,1.387786,10.827661,7.788797,5.318205,11.206312,1.825818,1.0,5.428668,11.794984,9.294897,9.520281
1,4.642600,2.164319,7.900627,11.031829,15.697125,4.966406,5.154928,15.944476,1.706946,1.0,13.513442,6.100469,6.021476,4.155357
2,12.304157,8.313284,11.444451,2.166363,6.304838,0.603777,12.916551,2.546260,3.280831,1.0,13.208962,12.038013,13.805481,0.067032
3,5.572493,10.054803,4.140951,4.689810,10.481349,1.492817,10.709971,5.197427,10.394042,5.5,11.056350,1.885446,8.463816,10.360725
4,17.911198,0.302719,2.802099,1.008775,6.823391,3.703310,0.070460,17.188845,9.172990,5.5,12.480050,2.867240,13.043743,7.125182
5,4.740944,16.029267,14.942933,2.787992,15.319728,8.870593,4.184193,4.148574,2.580989,5.5,6.709941,10.644299,2.821959,0.718588
6,11.844127,8.294827,5.502411,9.053567,2.229837,0.925552,8.295300,1.303896,11.241141,10.0,14.932989,1.537301,4.475018,10.364035
7,8.397772,9.441209,3.215412,3.319830,11.907548,7.891268,7.098224,4.573993,9.065075,10.0,2.440551,6.918210,4.315452,11.415455
8,9.808669,10.366759,9.985465,11.025185,7.673790,1.257879,11.200287,7.721844,1.651701,10.0,4.439759,5.701463,6.830073,2.337126

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,1.383833,1.773924,9.982101,10.592558,10.035200,4.170317,11.142084,8.481911,9.283513,9.616937,1.0,12.500611,9.597441,0.439569
1,1.493772,15.341303,8.152001,10.206315,9.144820,1.941894,10.085366,1.473917,6.562643,13.994903,1.0,3.446724,9.079377,8.076966
2,1.666695,11.118603,10.740377,2.764677,7.079728,3.596773,10.058032,14.903429,14.123007,1.875573,1.0,7.309180,7.253716,6.510210
3,2.493927,5.031502,4.240302,8.446596,4.852574,9.424528,9.795584,7.891606,11.742097,6.037524,5.5,11.347603,11.348873,1.847283
4,6.578229,10.564866,16.898958,3.858096,7.091505,4.282266,16.553274,4.401986,5.503239,2.573379,5.5,9.273043,3.527365,3.393794
5,10.527767,1.390704,6.673453,12.510434,4.069312,10.605114,0.330436,8.092717,7.566158,8.449326,5.5,12.501717,10.978788,0.804074
6,5.794072,13.701542,2.298138,1.295836,8.386067,9.112652,4.510269,6.892398,6.665933,8.568165,10.0,4.409173,13.053254,5.312501
7,18.371931,17.957176,1.874040,2.997364,7.104795,1.293003,0.805735,6.749383,15.776423,1.634704,10.0,2.435639,12.888222,0.111587
8,5.004222,2.860479,12.936782,3.195383,8.973677,9.564205,1.538617,6.642198,9.578660,9.579874,10.0,6.560807,3.263839,10.301257

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,14.286358,16.009179,8.966132,3.215723,1.597811,14.822824,7.949088,4.017949,10.290002,0.056183,7.664051,1.0,5.658558,4.466142
1,1.403417,0.059052,9.971481,8.424463,1.784633,12.518859,3.665834,16.460848,6.810396,13.029995,11.982861,1.0,0.216431,12.671729
2,11.771474,12.332298,0.285503,7.884222,9.015579,1.387376,5.757036,0.971588,12.013572,8.786996,15.065414,1.0,10.548091,3.180851
3,10.066197,5.610007,8.196540,9.659636,8.190584,9.086387,9.921962,7.768294,4.734929,6.707399,5.426954,5.5,8.454640,0.676472
4,6.760530,11.291317,12.148155,1.129624,12.013836,1.174995,9.976091,14.319878,9.379095,5.057619,0.276932,5.5,3.961297,7.010629
5,1.296182,6.544325,11.000623,11.570801,7.147014,1.602411,6.172320,4.277039,2.373280,6.944967,10.944849,5.5,12.053312,12.572878
6,11.523121,8.377220,1.537945,3.712015,1.970709,6.607013,10.854870,9.330803,1.453575,10.340538,4.519097,10.0,12.487778,7.285317
7,0.783920,8.087370,5.193129,12.012267,9.632567,11.207192,3.294232,11.398985,10.230412,3.972020,7.312092,10.0,0.783855,6.091960
8,8.847019,11.630937,6.038671,10.125676,3.697012,7.307393,5.327672,1.830706,4.894617,7.817566,9.467142,10.0,1.974120,11.041469

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,1.281618,13.132906,7.607692,1.500986,7.533305,0.208155,6.743230,10.919344,14.462855,4.195933,14.332264,9.649213,1.0,7.432500
1,1.538164,2.607008,7.656633,7.217874,6.782895,7.967835,14.852481,3.714194,4.041247,7.578198,14.513013,13.742724,1.0,6.787733
2,7.556832,7.648482,12.479448,13.194284,9.533009,11.133575,8.149912,1.085061,4.824299,2.233901,6.639512,8.247471,1.0,6.274214
3,5.037678,1.449297,11.343274,4.890714,12.280931,3.839822,11.247808,10.492486,2.253777,14.644434,7.372861,5.451020,5.5,4.195899
4,4.745010,0.831999,5.124844,0.529143,12.358458,3.323780,7.698373,6.276037,4.440861,12.064286,9.816675,16.989296,5.5,10.301236
5,8.793322,12.641026,6.639363,0.001980,2.368219,12.163288,2.689703,12.358230,12.262519,6.042257,5.010383,6.682303,5.5,6.847405
6,10.194110,3.118341,4.208968,11.002496,5.824663,2.875022,9.015770,6.029926,9.452895,15.458979,5.049820,2.628917,10.0,5.140092
7,8.378046,9.334628,5.496476,9.215666,9.357460,9.224405,2.947154,8.334196,4.882439,4.299471,6.152809,4.629992,10.0,7.747258
8,8.516783,9.312902,10.054490,1.369816,10.687133,2.834103,6.816407,7.317058,7.779030,7.697687,2.361783,4.677598,10.0,10.575212

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,10.080168,10.573579,8.728485,6.903640,2.319527,5.708345,12.053177,2.582995,5.917023,8.552017,12.220288,7.180478,6.180277,1.0
1,11.867793,2.384932,13.018177,0.282165,10.668361,5.505981,8.842199,2.757249,10.786870,13.365644,11.497304,4.309720,3.713603,1.0
2,12.304626,10.119918,1.679884,8.289479,5.534360,9.738934,10.896632,8.480551,11.409295,8.657862,3.931307,7.306564,0.650588,1.0
3,12.134013,12.147099,3.117549,12.347062,13.511240,4.795229,1.358771,0.529704,13.354361,3.304816,4.731698,4.361923,8.806536,5.5
4,5.502450,0.360634,10.161528,1.115868,11.118969,1.959012,11.308238,2.850122,14.672022,4.521732,7.824279,11.370289,11.734858,5.5
5,3.324016,8.470641,2.356043,2.744720,13.837753,13.667005,12.292209,1.539151,5.602212,10.159530,8.231184,10.640501,1.635032,5.5
6,10.711773,3.991261,11.388678,8.288181,11.223903,0.298117,5.677090,7.005891,7.240108,5.626233,6.695635,1.757906,10.095224,10.0
7,12.276970,1.049151,10.170276,4.096267,4.050654,3.596529,0.843490,10.778923,10.827654,5.719680,11.404675,4.207015,10.978718,10.0
8,8.532883,0.804048,8.707370,10.820840,6.467448,7.141448,11.487792,11.863529,7.285482,0.624566,0.854308,7.548624,7.861663,10.0

In [8]:
df_final.head()

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,1.0,4.242964,9.727991,2.487640,9.276884,14.262146,10.511050,2.714504,2.988385,11.723815,1.664164,12.540410,7.565846,9.294202
1,1.0,16.946883,4.901470,5.793087,6.941020,6.366080,5.600586,3.245494,10.738783,8.994274,3.969390,4.417968,7.698795,13.386170
2,1.0,7.310348,7.503049,8.641615,2.621892,6.432013,6.888139,7.257567,12.078934,13.761323,8.074576,11.290380,2.004406,5.135761
3,5.5,7.307491,5.512576,8.871160,8.575521,7.412665,9.197438,8.643014,5.346761,1.247877,11.123711,8.991908,12.083755,0.186123
4,5.5,8.022166,1.071140,9.539095,3.978240,8.826514,10.534063,8.330669,2.256654,1.802282,5.335602,12.678101,9.497714,12.627760

In [9]:
df_final.to_csv(outfol + '/combined.txt', sep='\t', index=False)