In [1]:
import numpy as np
import pandas as pd
import random as ran
import os

In [2]:
file_cn = 'Data/BL14_PhenoClass.txt'

transpose = True
header = None
index_col= True

lower_lim = 0.00001
upper_lim = 0.1

repetition = 10

mix_num = 25

outfol = file_cn+'_proportions'

In [3]:
if transpose:
    data_cn = pd.read_csv(file_cn, sep='\t', index_col=0, header=header)
else:
    data_cn = pd.read_csv(file_cn, sep='\t', header=header)

df_cn = pd.DataFrame(data_cn)

if transpose:
    df_cn = df_cn.T

df_cn.columns

Index(['CD4', 'CD8', 'nB', 'NK', 'Mn', 'mNeu', 'm8', 'DC', 'Eo', 'Tr', 'm4',
       'Mg', 'Er', 'mB'],
      dtype='object', name=0)

In [4]:
def generate_list(cell_name, cell_list, val):
    length = len(cell_list)
    vals = np.zeros(length)
    r = [ran.random() for i in range(1,length)]
    s = sum(r)
    r = [ (i/s) * (100 - val) for i in r ]
    name_seen = False
    for i in range(length):
        if cell_list[i] != cell_name:
            if name_seen == False:
                vals[i] = r[i]
            elif name_seen:
                vals[i] = r[i - 1]
        elif cell_list[i] == cell_name:
            vals[i] = val
            name_seen = True
    return vals

In [5]:
mixtures = np.linspace(lower_lim, upper_lim, num=mix_num) * 100
mixtures

array([1.000000e-03, 4.176250e-01, 8.342500e-01, 1.250875e+00,
       1.667500e+00, 2.084125e+00, 2.500750e+00, 2.917375e+00,
       3.334000e+00, 3.750625e+00, 4.167250e+00, 4.583875e+00,
       5.000500e+00, 5.417125e+00, 5.833750e+00, 6.250375e+00,
       6.667000e+00, 7.083625e+00, 7.500250e+00, 7.916875e+00,
       8.333500e+00, 8.750125e+00, 9.166750e+00, 9.583375e+00,
       1.000000e+01])

In [6]:
os.mkdir(outfol)
df_final = pd.DataFrame(columns = list(df_cn.columns))

In [7]:
# os.mkdir(outfol)

for cell in list(df_cn.columns):
    df_out = pd.DataFrame(columns = list(df_cn.columns))
    for val in mixtures:
        for i in range(repetition):
            arr = generate_list(cell, list(df_cn.columns), val)
            while 0.0 in arr:
                arr = generate_list(cell, list(df_cn.columns), val)
            df_out.loc[len(df_out.index)] = arr
    display(df_out)
    df_out=df_out.round(6)
    df_final = pd.concat([df_final, df_out])
    
    
    df_out.to_csv(outfol + '/' + cell + '.txt', sep='\t', index=False)

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,0.001,7.885888,2.172402,5.478062,12.513055,9.100476,5.106920,11.611825,10.871841,1.123017,1.059433,16.380862,7.448356,9.246863
1,0.001,0.515664,15.861884,9.626723,11.582871,14.465188,4.474178,6.371656,7.046899,12.120064,4.913278,5.276999,1.838617,5.904979
2,0.001,3.487170,6.667517,8.796901,11.762315,8.813112,1.305429,15.326116,10.264903,4.392718,11.110514,2.755270,11.134863,4.182172
3,0.001,3.417728,1.902984,15.545089,7.867087,0.922468,15.956744,16.541893,15.511330,7.561372,0.273998,2.296787,11.548417,0.653103
4,0.001,3.631581,6.115137,4.998415,6.026518,1.270327,14.014586,11.798737,4.215429,7.670527,8.949419,9.286673,4.291705,17.729946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,10.000,7.261002,2.918691,10.199067,1.993219,13.221373,10.124188,3.545360,1.504545,13.474502,17.581810,7.612580,0.021931,0.541733
246,10.000,10.563494,11.767027,6.629095,7.674324,0.846476,2.672671,9.015259,11.864191,5.949821,7.567833,6.090227,7.187166,2.172418
247,10.000,10.976788,5.126420,12.629942,1.761498,6.300852,7.192762,3.493408,1.991204,10.146984,3.265363,8.903440,5.301391,12.909948
248,10.000,9.717488,4.896586,2.945146,7.659255,4.311803,9.220180,10.311453,2.116614,9.885000,9.802685,5.950068,10.178860,3.004860
249,10.000,10.045808,6.480415,5.429931,9.046130,7.008383,5.599462,12.314080,3.540122,1.785408,8.137836,11.348892,5.164814,4.098719

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,7.561812,0.001,9.067515,5.763541,2.700997,7.248350,11.342797,7.630307,5.760212,3.792763,9.261378,5.802411,11.797257,12.269659
1,14.752729,0.001,11.295638,5.521529,1.957488,5.552207,7.154577,4.647092,11.923421,14.440251,0.200087,11.419656,0.287284,10.847042
2,1.206691,0.001,9.832900,4.773741,8.463511,3.962791,12.085489,2.990449,5.620722,5.608871,10.605800,8.894554,10.896424,15.057059
3,7.655591,0.001,8.913678,6.252811,14.082374,7.514149,12.247374,2.765654,5.652715,5.518549,13.870064,8.332453,2.878649,4.314940
4,5.269059,0.001,12.390125,2.220672,5.319311,4.048006,8.818668,10.121667,7.037506,8.830757,6.992529,4.629144,14.985843,9.335712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,1.786870,10.000,6.566059,7.295949,11.103356,8.080102,4.905294,8.308093,8.414025,6.988033,8.112775,1.046363,8.856020,8.537062
246,18.195672,10.000,0.866192,13.938589,1.790309,14.571598,5.349357,17.529049,4.425849,5.192915,2.054058,5.118456,0.815319,0.152639
247,10.829879,10.000,1.698010,6.065280,1.224635,5.457531,8.272091,10.362817,10.332892,11.049466,2.878598,8.221109,7.205651,6.402042
248,12.137156,10.000,4.044244,12.710133,10.005415,7.617215,1.446909,2.023934,5.031181,1.734872,3.187936,6.278099,12.199107,11.583799
249,5.281868,10.000,4.301057,9.698419,9.693774,2.751479,2.252626,14.442371,7.550765,7.128052,4.151147,9.832669,7.769808,5.145965

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,12.565603,8.833222,0.001,11.712087,6.828340,8.332081,5.937334,1.552069,6.821362,7.917644,12.546769,3.731075,11.607124,1.614290
1,13.394143,4.323456,0.001,13.695236,9.649745,1.946476,9.584780,2.208588,13.656705,7.455049,0.952913,15.663692,4.941087,2.527130
2,2.135573,6.837758,0.001,7.405522,12.915714,10.363010,18.164516,9.734585,3.450597,5.012328,3.337321,4.815313,9.452056,6.374706
3,13.262087,11.762258,0.001,3.223572,0.547018,6.527131,7.374338,12.374281,6.847201,6.984340,12.860099,9.094960,5.896505,3.245210
4,12.928568,9.878355,0.001,3.643388,3.101485,1.018196,12.589314,11.610772,12.976633,4.882003,4.758084,2.030884,8.232215,12.349104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,6.156403,13.668954,10.000,9.574889,4.901536,9.909217,0.003524,5.106216,5.527138,9.111395,5.839323,11.890964,4.687769,3.622672
246,4.510309,10.063191,10.000,9.034903,0.934091,12.158832,3.333171,10.077539,9.557282,2.904088,12.881007,3.956803,5.486868,5.101917
247,1.279714,8.592837,10.000,4.803369,5.542875,1.236814,15.867952,8.720077,5.405249,8.788012,2.671248,1.415674,16.435865,9.240314
248,12.057296,6.196836,10.000,5.527859,8.155760,7.110210,12.690653,1.252678,4.147079,4.259507,8.110882,5.882931,2.099753,12.508556
249,8.027814,6.798021,10.000,6.736893,8.190079,5.197389,3.235399,1.689210,9.923410,6.179045,9.225811,7.324764,8.865990,8.606176

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,5.361590,8.053424,4.632427,0.001,1.699998,9.948773,6.368666,9.348075,7.883378,12.981544,13.531951,2.218021,3.847798,14.123356
1,6.529879,12.763743,7.122264,0.001,7.333119,12.895374,14.437824,7.675247,1.024714,4.914288,0.472960,5.482704,7.324948,12.021937
2,7.530825,9.608453,2.936664,0.001,5.678270,10.506456,5.762554,10.581111,1.573048,10.877710,9.715417,10.920656,7.381608,6.926229
3,14.851746,8.982040,3.858628,0.001,5.871836,12.273879,10.635418,5.702581,0.026026,17.184409,16.175003,0.931083,2.470710,1.035641
4,7.257968,13.667035,12.657427,0.001,0.490559,3.446482,8.702517,8.084648,4.392291,12.285909,1.753371,13.862984,12.201715,1.196093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,6.393556,8.400537,0.064889,10.000,8.318703,11.661661,0.993804,7.215810,12.370332,10.228063,6.583352,9.204887,1.673332,6.891072
246,10.885678,1.560874,3.348073,10.000,2.183382,7.580695,12.924191,10.572180,5.331630,12.409293,0.862539,1.903478,10.300076,10.137913
247,8.583737,0.778131,11.895303,10.000,0.491425,12.891618,9.331565,0.166541,14.298093,8.737905,8.725709,6.422262,2.183713,5.493998
248,7.071255,8.805393,6.181065,10.000,11.077982,3.911402,5.624086,5.547280,4.315469,1.149905,10.191449,6.785611,9.731488,9.607614
249,6.470628,8.243116,10.298451,10.000,9.976780,0.780405,8.802662,8.236668,4.889874,3.959997,9.053951,8.135041,6.252674,4.899751

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,10.646670,10.426845,9.131410,10.201928,0.001,5.125344,15.194955,2.481586,7.361449,8.419123,12.191263,1.539874,1.303258,5.975296
1,6.784406,2.683870,7.853961,11.884458,0.001,4.405917,10.670380,7.537135,7.210727,8.222113,4.233119,10.710656,7.792552,10.009706
2,11.969773,2.433916,16.354745,13.734827,0.001,11.310864,5.253649,15.265608,4.744588,1.092711,5.686651,8.415729,1.754888,1.981052
3,13.179480,13.468696,8.686121,0.516738,0.001,8.956795,1.246061,5.129992,3.601492,5.871357,11.280265,6.965456,7.612746,13.483801
4,12.018648,10.329031,4.935408,5.620893,0.001,5.358677,13.694452,1.992489,2.122482,14.045148,6.293886,7.604496,10.434342,5.549047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,3.127566,10.703016,15.262289,12.127192,10.000,10.371041,4.484865,15.076075,3.014088,5.763551,4.031400,1.173440,2.449337,2.416140
246,11.133629,0.442663,12.897052,10.370166,10.000,12.160179,3.064346,4.426669,3.403118,0.882321,12.767370,6.758976,5.701226,5.992284
247,2.866305,7.605436,2.212804,7.049187,10.000,9.174540,13.337114,1.270241,8.695895,9.809651,9.504016,13.661864,1.227615,3.585331
248,11.751373,10.790781,11.113173,2.992490,10.000,5.991305,2.831018,0.191817,8.239679,1.071600,7.913072,13.045749,5.213093,8.854849
249,10.663512,4.491240,9.970574,4.912319,10.000,10.077429,9.037590,1.330918,11.463682,1.301081,1.013457,7.290087,8.696472,9.751641

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,13.906911,8.251255,0.936505,5.132632,11.366224,0.001,15.114565,7.755967,8.223201,3.559477,1.357433,11.656298,3.518343,9.220187
1,11.788744,12.732158,8.088228,11.527159,0.199680,0.001,9.624925,7.550454,5.082848,6.508283,5.570957,9.962765,8.810238,2.552562
2,7.205583,8.399026,5.994165,9.051349,16.924675,0.001,2.418857,18.715459,9.538476,3.379296,1.720343,1.011673,8.032254,7.607843
3,12.735432,7.704763,5.356903,15.274928,8.602361,0.001,1.542629,8.839942,13.804956,6.314955,4.883462,5.104459,1.200183,8.634028
4,3.036703,11.262896,0.448085,14.545305,11.709728,0.001,8.853232,2.667921,11.014935,0.722913,13.860239,8.051771,3.969250,9.856022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,6.080795,10.709856,10.882657,4.457462,13.957636,10.000,7.444648,1.606130,4.138445,2.741003,15.971775,1.309908,4.995031,5.704655
246,11.077079,4.628674,2.304531,8.416200,4.740617,10.000,12.055780,8.504494,10.546321,11.854457,1.035692,4.647726,9.561178,0.627251
247,8.495234,9.248380,7.786279,3.731024,10.080852,10.000,4.984517,11.261446,6.860098,2.614692,1.593421,6.055673,6.722028,10.566356
248,6.126943,5.069648,16.699754,12.135136,2.341872,10.000,0.831403,10.682718,7.182827,3.897959,3.617536,13.493287,7.125452,0.795465
249,5.128167,3.793397,0.893106,5.157374,6.543697,10.000,12.463896,2.315724,6.777191,10.365239,12.229192,8.039043,13.747900,2.546075

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,0.784832,7.174487,3.507282,12.386386,4.682209,5.115038,0.001,16.838297,16.656794,4.455553,4.431213,7.281258,2.802678,13.882970
1,1.730694,16.541830,6.697754,13.019786,5.147832,6.250063,0.001,12.444120,11.669214,5.048684,2.992933,2.031692,9.667819,6.756581
2,0.690104,14.902028,11.530753,9.733026,6.509507,12.010414,0.001,3.370535,11.723598,13.451206,4.220188,8.180839,1.302397,2.374407
3,4.136252,13.178983,12.269971,5.751845,1.823340,8.987213,0.001,7.291590,8.105785,13.051106,7.480627,2.091220,7.885242,7.945826
4,8.328646,7.260964,10.468030,8.382256,0.784066,1.228922,0.001,11.754771,10.769633,6.850221,7.800194,5.929965,8.832505,11.608825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,9.762347,9.580269,4.125154,8.495879,5.029523,9.141704,10.000,6.786579,4.232939,4.116244,5.045450,9.068819,4.747642,9.867451
246,15.990873,15.289232,9.175669,1.543263,1.803675,1.967493,10.000,12.423953,3.797496,5.123608,5.080849,5.139929,11.553289,1.110671
247,7.565720,10.100535,1.755425,4.616165,10.887272,10.028467,10.000,7.036465,4.642314,4.974451,8.302105,0.326192,12.934883,6.830006
248,8.031618,0.321089,4.233445,2.137435,0.470300,3.991514,10.000,8.931061,9.837696,16.627465,8.487065,1.766847,12.553986,12.610480
249,5.321975,10.949324,9.876766,7.564573,2.601325,10.296081,10.000,9.713641,1.502846,3.424635,10.658535,8.063726,0.977523,9.049050

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,6.849812,4.631540,0.433564,6.396806,17.878973,1.571212,9.778800,0.001,2.933731,3.261168,8.319951,17.030488,4.751682,16.161272
1,11.103764,5.370826,9.463014,7.608245,11.135905,9.795449,1.886459,0.001,9.120192,7.456366,9.757159,10.682657,6.264282,0.354684
2,1.131117,5.885924,14.979867,1.179999,2.792052,16.507002,3.504680,0.001,7.504856,7.002615,15.039647,15.581670,1.725230,7.164341
3,2.514619,10.380251,11.088412,2.387410,4.040498,5.617454,10.372424,0.001,1.901740,10.046647,8.326837,11.376524,11.101462,10.844722
4,0.254441,2.686619,11.349128,5.694499,2.124326,8.436695,8.903871,0.001,10.326680,16.192889,9.811650,9.057729,13.039988,2.120486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2.571258,9.599439,10.125320,6.097123,5.164123,7.848906,2.193079,10.000,8.603086,9.072230,6.929607,9.448693,10.931542,1.415595
246,7.609788,11.080966,2.539765,9.607854,11.568932,11.172333,4.114343,10.000,6.236997,0.881471,5.215609,5.719539,1.483172,12.769231
247,4.699229,4.967465,3.128183,0.956981,11.528131,1.125012,5.981133,10.000,10.739972,8.036629,15.493003,16.398208,4.615153,2.330901
248,2.802921,6.899077,7.092095,4.112185,7.514160,3.923964,12.899057,10.000,1.556832,12.389116,12.048041,3.329294,6.746016,8.687242
249,2.734734,11.055733,11.547541,7.720509,10.295991,6.332426,10.617439,10.000,0.683993,3.106849,0.351791,12.216427,8.453558,4.883008

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,7.155959,12.240261,12.198155,4.141554,7.989077,7.928477,12.617013,6.291118,0.001,11.382697,9.097454,0.619406,8.049723,0.288106
1,8.913939,13.178943,5.175880,5.266392,12.466865,3.106461,0.453494,7.056488,0.001,8.194007,10.225762,11.139961,9.459407,5.361402
2,12.226345,2.416544,9.960372,8.457860,8.947345,10.788543,1.888019,0.951945,0.001,11.352354,9.600489,9.017868,7.873197,6.518119
3,11.704819,10.605338,7.554103,18.404982,9.764601,9.012522,2.289009,7.881716,0.001,5.823675,2.312064,2.298955,5.280763,7.066453
4,7.548733,8.203772,6.920491,2.681297,8.468423,9.999135,13.541193,3.252420,0.001,2.738919,12.662705,14.641313,5.043327,4.297272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,12.717099,0.804842,5.048807,11.082341,10.025179,5.532605,3.809812,11.898234,10.000,6.158622,1.672565,10.059368,2.836278,8.354248
246,0.947131,1.082340,3.630327,1.871521,1.862006,9.834638,15.989784,9.338093,10.000,12.722618,18.360051,2.119444,1.722985,10.519062
247,3.738054,15.042467,11.750340,11.839220,1.157082,3.221576,8.188124,12.136994,10.000,14.018134,1.529726,0.543896,3.132414,3.701971
248,1.725108,0.774630,10.348637,8.677576,9.222008,6.718192,6.520566,9.424411,10.000,13.910433,2.461984,0.271139,4.725964,15.219352
249,9.470118,2.442275,9.173756,6.808319,10.971457,5.571925,5.939102,3.491475,10.000,3.330477,10.456818,7.754529,8.255023,6.334726

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,7.751646,9.157199,2.322055,10.483021,9.195374,15.117315,10.265043,1.035511,7.364871,0.001,0.889734,3.844924,15.000055,7.572253
1,3.973509,9.439645,6.603084,5.330695,13.220580,1.413228,8.179594,11.800064,3.625540,0.001,8.402071,12.180547,9.279919,6.550525
2,3.561615,2.061029,18.780043,2.541418,0.915662,5.021652,6.159381,17.202226,17.005762,0.001,8.803745,11.787771,1.623143,4.535552
3,10.101359,1.464482,5.877473,7.469100,10.280863,12.606054,10.814664,1.950097,4.495040,0.001,9.459999,12.121409,11.288895,2.069568
4,9.420890,12.716007,0.417089,10.672700,6.242721,2.992120,12.459873,12.807704,7.810632,0.001,7.517771,10.006292,2.678516,4.256683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,6.867871,18.357033,2.169655,2.714278,8.332720,14.428741,0.544181,9.751452,2.334166,10.000,9.109132,1.719976,10.110562,3.560233
246,0.352922,7.473239,9.863554,1.909902,10.584415,13.145016,7.875980,5.320142,2.150313,10.000,2.746355,14.865008,1.827883,11.885270
247,0.122064,5.298713,13.359424,1.268743,10.019699,5.201611,12.028610,9.032905,11.158232,10.000,7.243884,5.737635,6.791423,2.737056
248,5.354139,4.663845,8.615418,13.799908,7.762003,5.269074,5.266538,12.935995,4.882426,10.000,1.276854,7.986533,7.441825,4.745443
249,2.927663,5.712276,12.635119,1.428374,6.886295,3.727613,12.320186,12.610422,9.034596,10.000,1.465968,9.010775,4.807160,7.433554

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,0.061656,9.008470,6.867616,13.618658,8.882726,8.812095,3.249379,12.778316,12.705011,11.174954,0.001,3.966024,6.650235,2.223860
1,12.822688,5.082205,13.079351,6.053281,12.446847,7.024166,9.091950,10.804576,0.336842,4.767275,0.001,6.783086,8.643116,3.063619
2,15.444032,0.409744,9.147935,12.268943,10.460247,3.988947,9.973658,8.689068,11.736618,3.092361,0.001,4.605404,2.020545,8.161498
3,12.286817,7.028918,15.965720,2.564319,4.006730,9.791036,2.390962,3.588861,10.166379,5.157391,0.001,14.425422,4.185253,8.441191
4,9.375092,4.393401,3.504875,5.497305,6.752292,8.827410,9.442228,7.098082,6.528917,10.623841,0.001,7.441551,11.567063,8.946944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,3.127266,9.012998,0.524084,13.092988,10.077402,9.274614,12.386853,2.687229,1.384492,2.502376,10.000,11.090165,10.552588,4.286944
246,9.261338,10.715696,6.051012,2.303792,2.402853,11.400580,1.737274,8.446123,9.336937,10.185888,10.000,4.393525,11.853221,1.911763
247,3.992946,0.204371,8.155495,7.859063,8.901420,8.481100,11.238675,1.634926,5.297749,13.418230,10.000,1.801385,13.261315,5.753325
248,2.571067,0.941038,6.848792,11.140643,4.279455,14.142957,15.422434,3.127652,3.739395,4.874946,10.000,14.035724,4.722803,4.153094
249,4.613078,12.548763,3.430416,12.660998,10.184753,3.913020,11.405196,0.226270,5.568067,3.703184,10.000,5.781733,10.138627,5.825895

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,15.408491,3.710526,12.955739,0.208678,1.909109,6.986136,1.129631,15.321241,2.209338,5.759476,13.778865,0.001,6.230824,14.390947
1,13.872809,6.310301,6.088772,14.755813,6.395519,12.565994,10.234546,2.315587,13.190984,0.625382,0.695244,0.001,0.920864,12.027185
2,9.548331,2.699416,1.657861,12.687176,5.811150,9.544218,0.831301,13.877219,6.648362,7.108741,15.073970,0.001,9.911262,4.599993
3,9.717640,3.052052,14.191385,12.879796,1.111087,14.072410,13.308485,9.433541,8.894712,3.613538,4.799747,0.001,3.187974,1.736633
4,10.484085,8.531805,4.911714,11.394813,1.835684,12.218858,11.143215,11.299061,9.532125,2.048289,5.831045,0.001,10.629769,0.138535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,4.174798,3.893564,11.882538,0.068122,7.385282,1.405240,7.289214,9.483876,7.648393,8.555137,10.621099,10.000,11.601219,5.991517
246,14.381105,1.705239,6.774830,3.446315,6.885239,1.924314,14.718419,13.410483,14.848841,1.327637,4.404156,10.000,4.842851,1.330571
247,13.301879,1.563357,7.775193,2.831018,12.495978,2.616227,0.382608,7.672710,7.452315,4.813669,11.821469,10.000,8.734118,8.539460
248,2.636268,4.472383,14.740230,0.623212,8.126914,3.332463,15.943526,9.179571,6.140100,5.331563,6.051673,10.000,10.080153,3.341942
249,17.935781,2.912036,11.955416,14.845110,4.666729,7.100260,1.227922,9.579684,3.225684,9.760329,3.221750,10.000,3.557968,0.011332

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,3.759123,13.298320,9.453183,8.472511,10.336172,9.731263,5.675876,13.672805,2.533338,13.329080,1.458996,8.225952,0.001,0.052381
1,14.522537,12.264953,1.972348,3.759042,1.766300,8.039805,14.586978,4.110750,13.326579,0.662911,12.848142,8.309481,0.001,3.829174
2,11.003397,2.751903,0.251864,8.607135,14.728070,1.328935,7.047987,14.266550,15.880357,1.196848,15.367169,1.679543,0.001,5.889243
3,5.555769,4.966148,0.616942,4.727912,10.993141,5.531554,7.841130,4.029126,10.674686,13.362169,9.829174,11.844263,0.001,10.026985
4,4.559395,10.127241,12.957831,8.628703,8.814438,5.708588,2.126566,6.816778,12.345989,10.841806,9.203305,3.096188,0.001,4.772173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,4.903461,5.073856,8.029831,8.277718,10.853402,0.815294,7.949666,0.499659,9.843171,10.076682,4.697629,9.034024,10.000,9.945607
246,11.128371,6.161046,7.705752,1.092830,6.311173,8.888687,11.165090,6.783358,11.292328,5.038124,0.592199,1.367567,10.000,12.473474
247,5.589318,3.691509,7.747789,6.929020,6.082528,6.925641,4.621158,9.502635,11.171776,10.067343,9.859562,0.952460,10.000,6.859262
248,12.661516,7.091272,2.571936,1.271642,1.345253,14.107155,8.414320,2.529569,13.055351,2.733054,6.687417,11.787741,10.000,5.743776
249,12.010259,0.942023,8.639884,5.500519,1.684170,3.009605,5.062039,8.787257,5.498927,12.090497,10.372749,11.488797,10.000,4.913273

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,12.921937,8.054789,6.097162,9.869048,8.117872,6.208224,8.728688,7.625093,3.847388,3.935711,4.098445,11.746617,8.748027,0.001
1,0.143612,1.145358,1.495787,10.233517,5.089684,11.200100,1.918232,14.827643,13.394086,9.340490,12.623548,8.757714,9.829229,0.001
2,3.714630,6.910086,5.570407,13.306534,13.514044,3.939135,8.096250,11.953438,4.528086,4.125354,5.485679,5.204382,13.650974,0.001
3,11.078354,6.839081,2.204921,8.504160,11.411819,9.055355,4.325410,12.942192,11.711913,2.317748,0.857079,10.253101,8.497868,0.001
4,9.887386,6.438513,4.064934,12.013292,11.345703,8.773443,7.512426,6.636326,6.164037,4.779532,10.112917,0.406945,11.863546,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2.427099,5.899836,9.582489,2.393860,2.236699,10.000088,13.466546,5.633018,3.364562,2.844424,9.512046,7.870497,14.768837,10.000
246,7.939919,7.588670,6.109138,9.239822,8.394175,7.806622,2.136942,7.544662,6.703845,4.106783,9.262694,5.018848,8.147881,10.000
247,9.106552,5.679746,6.533192,2.196450,1.555750,11.570929,3.923130,5.837298,6.403673,10.388433,8.781715,11.160932,6.862199,10.000
248,7.719456,1.297019,10.739957,11.809780,2.485428,10.502661,7.970212,5.391731,6.903341,2.812827,12.988784,4.472383,4.906423,10.000
249,12.932497,2.289463,6.955873,0.058862,9.264189,13.329953,8.565341,3.878877,8.513392,6.737032,8.207372,2.874845,6.392304,10.000

In [8]:
df_final.head()

,CD4,CD8,nB,NK,Mn,mNeu,m8,DC,Eo,Tr,m4,Mg,Er,mB
0,0.001,7.885888,2.172402,5.478062,12.513055,9.100476,5.106920,11.611825,10.871841,1.123017,1.059433,16.380862,7.448356,9.246863
1,0.001,0.515664,15.861884,9.626723,11.582871,14.465188,4.474178,6.371656,7.046899,12.120064,4.913278,5.276999,1.838617,5.904979
2,0.001,3.487170,6.667517,8.796901,11.762315,8.813112,1.305429,15.326116,10.264903,4.392718,11.110514,2.755270,11.134863,4.182172
3,0.001,3.417728,1.902984,15.545089,7.867087,0.922468,15.956744,16.541893,15.511330,7.561372,0.273998,2.296787,11.548417,0.653103
4,0.001,3.631581,6.115137,4.998415,6.026518,1.270327,14.014586,11.798737,4.215429,7.670527,8.949419,9.286673,4.291705,17.729946

In [9]:
df_final.to_csv(outfol + '/combined.txt', sep='\t', index=False)